### ISSUE TITLE
from requests.packages.urllib3.contrib.pyopenssl import get_subj_alt_name - ImportError: cannot import name get_subj_alt_name

### ISSUE THREAD

**Issue by hungaborhorvath** [linkchecker/linkchecker#101]
Original issue report is here: https://github.com/wummel/linkchecker/issues/701

Running the following on Raspberry Pi 2 with Raspbian Jessie warned about an internal error (see ````nodebug.txt```` attached).

````
linkchecker --no-status --no-warnings --check-extern -v -r 1 -F text http://zagor.hu/?oldal=letoltes >nodebug.txt 2>&1
````

I attached the output file, as well (````linkchecker-out_nodebug.txt````)

I ran the same command with ````-Dall````, as well, attached the corresponding files (````debug.txt```` for terminal output, ````linkchecker-out_debug.txt```` for the file produced by linkchecker). 

[debug.txt](https://github.com/wummel/linkchecker/files/692011/debug.txt)
[linkchecker-out_debug.txt](https://github.com/wummel/linkchecker/files/692012/linkchecker-out_debug.txt)
[nodebug.txt](https://github.com/wummel/linkchecker/files/692013/nodebug.txt)
[linkchecker-out_nodebug.txt](https://github.com/wummel/linkchecker/files/692014/linkchecker-out_nodebug.txt)
[debug.txt](https://github.com/linkcheck/linkchecker/files/1434483/debug.txt)
[linkchecker-out_debug.txt](https://github.com/linkcheck/linkchecker/files/1434484/linkchecker-out_debug.txt)
[nodebug.txt](https://github.com/linkcheck/linkchecker/files/1434485/nodebug.txt)
[linkchecker-out_nodebug.txt](https://github.com/linkcheck/linkchecker/files/1434486/linkchecker-out_nodebug.txt)

**Comment by cjmayo** [comment]
Key info form the debug log:

```
from requests.packages.urllib3.contrib.pyopenssl import get_subj_alt_name
ImportError: cannot import name get_subj_alt_name
```

This is not a LinkChecker error but a missing piece of supporting software.

Maybe an historic issue with older versions of requests and urllib3? Installing LinkChecker with pip today should be fine.
