### ISSUE TITLE
Qt4 is unsupported: port to Qt5?

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#105]
We have been [notified](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875032) in the Debian issue trackers that linkchecker (or at least its GUI part) could be removed from Debian because it depends on the Qt4 toolkit, which has been [unsupported since December 2015, with the 4.8.7 release](https://blog.qt.io/blog/2015/05/26/qt-4-8-7-released/).

That is reassuring:

> With a high degree of source compatibility, we have ensured that switching to Qt 5 is smooth and straightforward.

So presumably we may be able to build linkchecker against Qt5 as is - we are already building against 4.8.7 in Debian stretch and it works fine. But that needs to be tested!

If that fails, I'm not sure I have the energy to port linkchecker's GUI (which I don't use) to a newer framework, so I'm ready to disable the GUI in Debian to save it from being removed completely.

**Comment by anarcat** [comment]
And here's the [porting guide](http://doc.qt.io/qt-5/portingguide.html) - the biggest thing is probably the Qt3Support removal, if we're using that...

**Comment by cjmayo** [comment]
Proposed PyQt5 conversion here:
https://github.com/linkchecker/linkchecker-gui/pull/4

As the GUI has been removed from this project I suggest raising further issues in https://github.com/linkchecker/linkchecker-gui/issues.
