### ISSUE TITLE
Does LinkCheck check css links?

### ISSUE THREAD

**Issue by crazy-projects** [linkchecker/linkchecker#111]
As the title says, if i have something like:
background-image: url(http://mypartybynoelia.es/wp-content/uploads/2014/03/coleccion-metálicos1.jpg)
in a css file, or embeded in html, will linkcheck verify it?

Quick trials shows that linkcheck ignores css files, but maybe i'm missing some important point,

**Comment by reinholdfuereder** [comment]
Hm, when using `-v` option you might see whether or not the CSS files themselves are already skipped (mind the `Access denied by robots.txt, checked only syntax` info):
```
URL        `<DOMAIN>/cache/header/165805/5c20c56a6451058afc51a19573f2cd44.css'
Parent URL <the parent URL containing DOMAIN>
Real URL   <DOMAIN>/cache/header/165805/5c20c56a6451058afc51a19573f2cd44.css
Check time 0.002 seconds
Info       Access denied by robots.txt, checked only syntax.
Result     Valid: syntax OK
```

However, I am not sure about the support of links etc **in CSS files**...

**Comment by anarcat** [comment]
i do not believe CSS file contents are parsed, so the answer here is probably no.
