### ISSUE TITLE
README.rst vs. install.txt contradiction & installation on Windows

### ISSUE THREAD

**Issue by uahim** [linkchecker/linkchecker#124]
I'd like to upgrade to this new version because of Bastian's build fails on SSL/TLS sites.

now, README.rst states "pip install linkchecker should NOT be used for now" while doc/install.txt says "pip install LinkChecker" or recommends to "Execute LinkChecker-x.y.exe and follow the instructions." to Windows users - though there are no Win builds at all in this repository.

did any Win users manage to get this installed?
thanks

**Comment by toohoo** [comment]
Why does nobody answer this question? I came to the same point. In /doc/install.txt is described, what @uahim mentioned too. How should some Windows user install it on Windows?
Please respond urgently. Thanks in advance

**Comment by uahim** [comment]
nobody?

**Comment by uahim** [comment]
@anarcat thanks; maybe a quick note like on the main page would avoid confusion for other Win users :)

looking forward to a pypi version.

**Comment by anarcat** [comment]
so I guess we can keep this closed as a dupe of #53
