### ISSUE TITLE
The Icon in the .desktop Launcher has a broken link 

### ISSUE THREAD

**Issue by ElectricPrism** [linkchecker/linkchecker#129]
/usr/share/applications/linkchecker-gui.desktop

The Icon link on line 11 is broken when I install on Arch Linux
https://aur.archlinux.org/packages/linkchecker/

![screenshot from 2018-02-13 14-12-07](https://user-images.githubusercontent.com/635971/36176574-e6e20f74-10c7-11e8-936c-ce0c5b3dc8cb.png)

**Comment by mgedmin** [comment]
Our doc/linkchecker.desktop has

    Icon=logo48x48

which is not good.  `Icon=linkchecker` would make more sense, as long as the icon gets installed in `/usr/share/icons/hicolor/<size>/linkchecker.png`.

Still, we're not currently publishing any installers anywhere, so the issue ought to be fixed by the people who do (the ArchLinux maintainers in this case).

**Comment by ElectricPrism** [comment]
I noticed that these seems to be icon sizes available at:

`doc/web/media/images/logo48x48.png`

For clarification Archlinux has it available as a AUR which builds directly from git [as seen here in the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linkchecker#n9).

If you'd like I can request that code be added to copy those icon files to those locations however it won't resolve the issue should anything `git clone` it themselves and do `make install`

**Comment by anarcat** [comment]
seems like using `Icon=linkchecker` would be a good start already. Otherwise, yes, forward this to Arch by all means.

**Comment by cjmayo** [comment]
The GUI (and its desktop file) has been removed from this project.

I have fixed the desktop file in the proposed update to the GUI:

https://github.com/linkchecker/linkchecker-gui/pull/4/files?file-filters%5B%5D=.desktop#diff-61e440091adaf27c0c374d7571fbc839
