### ISSUE TITLE
[meta] how do members get demoted?

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#139]
while reviewing our contribution guidelines in #138, I realized we had no formal way of removing disappeared or idle maintainers, at least not explicitly in the Membership section. and now I need approval from @davejagoda and @seamang to do what are after all rather trivial changes to the contribution guidelines. are you guys still around? :)

even if our folks are still active, this raises the question what should we do with inactive maintainers. I'm tempted to put a timeout on review requests after which those can be bypassed. i'm also tempted to remove the concensus clause from the guidelines completely to avoid this problem in the future without having to hardcode stuff about how to remove maintainers explicitely. 

thanks for your feedback!

**Comment by mgedmin** [comment]
A timeout of reasonable length (somewhere on the order of 1 week to 1 month?) sounds like a good idea.

**Comment by anarcat** [comment]
okay, let's propose 1 month timeout as a first guideline. should i bundle this in #138 or separately?

**Comment by mgedmin** [comment]
Currently I assumed/hoped #138 was splitting the guidelines into two documents without making any semantic changes.  The way the diff gets computed would make those too hard to notice.

**Comment by anarcat** [comment]
On 2018-03-26 23:20:41, Marius Gedminas wrote:
> Currently I assumed/hoped #138 was splitting the guidelines into two documents without making any semantic changes.  The way the diff gets computed would make those too hard to notice.

Makes sense.

**Comment by anarcat** [comment]
the thing is we can't seem to merge #138 because @seamang is unresponsive. :) furthermore, because of the new org change related to the namespace issue (#136), @seamang is not actually part of the members here anymore. so effectively, we've gone through an informal 4-week timeout now, and I would propose we merge #138 as is now, and make another patch with an explicit timeout.

**Comment by seamang** [comment]
Sorry - I left the job this account was linked to so have not been receiving mails etc. Can you remove me from the maintainers list? I might participate later using my personal account , but not for now. Sorry for holding things up.

**Comment by anarcat** [comment]
@seamang you were already not on the new organisation here, so i just removed your invitation and removed you from the previous project. sorry to see you go, but thanks so much for responding and contributing what you did! :) you will always be welcome here.

**Comment by anarcat** [comment]
so i think the next step here is another PR to amend the contribution guidelines to add a timeout.
