### ISSUE TITLE
move website out of this repo and into RTD

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#142]
nevermind history, the whole git repo is still in `doc/web` here. we should just remove this whole thing - i don't understand why it's there *and* in the `gh-pages` branch. i understand the gh-pages is only a rendering, but we should not duplicate content like this without purpose.

note that those directories are not in the exported tarballs because of an exception in `.gitattributes`. we shouldn't need such a hack either. i also noticed a `.rej` file lying around the website which was detected during the debian package build as part of the last release in #141.

kind of a mess. :) IMHO, we should just use a standard Sphinx-style website instead of some weird site like this. then the site can link to GitHub releases and PyPI instead of duplicating tarballs like this. this would also make the repository much slimmer and easier to clone.

**Comment by mgedmin** [comment]
Sphinx is good.  ReadTheDocs are good.

You need the `gh-pages` branch if you're planning to host something on GitHub pages.  (And, in several cases, I've found it very helpful to have rendered static HTMLs preserved in a branch when the main website fails to rebuild correctly due to backwards-incompatible changes in $popular_static_website_generation_tool_of_the_day.  Tools like [ghp-import](https://pypi.org/project/ghp-import/) help keep it updated.)

**Comment by anarcat** [comment]
Yeah I wouldn't mind having a minimalist site like we have now, but ripping out the download links completely, fixing #5 in the process... But the manpages, documentation, all that stuff should be in a documentation site.

We can do this incrementally of course, starting with #5 and then converting all of `doc/` into a proper sphinx tree.. But I figured I would at least document the SNAFU I've established in the Debian package somewhere. Eventually, I think we want to move `doc/web` out of this repo into a `linkcheck.github.io` repository or something...

**Comment by anarcat** [comment]
i've opened #145 to remove binaries from the website. we can use this issue to track a future move to RTFD.

**Comment by thorade** [comment]
There are three possible sources for github pages:
* a docs directory on the master branch
* all files on gh-pages branch
* or all files in a repo named username.github.io 

Out of these three, I would consider the gh-pages branch the one that is the least obvious or most hidden.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by anarcat** [comment]
i think the first option ("docs directory") is what is being considered here, with "read the docs" as the publisher/builder and Sphinx as the format.

**Comment by cjmayo** [comment]
I think we have a satisfactory solution now with automated publishing of Sphinx to the gh-pages branch. RTD can have advantages (e.g. if supporting multiple versions of documentation), but membership of another site to manage...

**Comment by mgedmin** [comment]
Let's tag it postponed then and close for now.  If anybody wants to champion a move to RTD, we can reopen.

**Comment by anarcat** [comment]
point of this issue was mostly to remove the duplication between doc/web and the gh-pages branch. if that's fixed, i'm glad the bug is closed. :)
