### ISSUE TITLE
remove binary files from website

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#145]
as a stopgap measure before we fix automated builds in #5, i think we should just remove the old binaries from the website: they are broken and just lead to support requests and confusion and make github unhappy.

**Comment by mgedmin** [comment]
What is "the website" you're speaking of?

We have no access to make changes to https://wummel.github.io/linkchecker/, which is hit number 2 on Google for "linkchecker" (the 1st hit is validator.w3.org).

**Comment by anarcat** [comment]
i'm refering to https://linkcheck.github.io/linkchecker/

of course we're stuck with the old wummel site too :/

**Comment by mgedmin** [comment]
(For the record I was confused by https://linkcheck.github.io/ being a 404 page and didn't notice we had a website at /linkchecker/.)

**Comment by anarcat** [comment]
(re. wummel.github.io, i've added that to the checklist in the namespace issue for now)

**Comment by cjmayo** [comment]
No binaries visible on https://linkchecker.github.io/linkchecker/ now.
