### ISSUE TITLE
Feature Request - disable "intro"

### ISSUE THREAD

**Issue by peterhoeg** [linkchecker/linkchecker#146]
linkchecker writes a lot of junk to stdout when launching:

```sh
./linkchecker https://example.com
INFO linkcheck.cmdline 2018-04-13 15:57:51,210 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html
```

Apart from the fact that the links are wrong, it would be great to be able to pass a flag that makes linkchecker not show the license/version/copyright/links.

**Comment by anarcat** [comment]
the broken links issue is #110.

as fort he verbosity, i think it would be fine to move that cruft to --help or --version flags.

**Comment by thezoggy** [comment]
any plans to add this?

**Comment by cjmayo** [comment]
There is already the "parts" setting in linkcheckerrc i.e. don't include the "intro" logger part:

https://linkchecker.github.io/linkchecker/man/linkcheckerrc.html#text
