### ISSUE TITLE
LinkChecker 9.4 has requirement requests<2.15,>=2.2

### ISSUE THREAD

**Issue by SilkAndSlug** [linkchecker/linkchecker#149]
Calling `pip check` returns `LinkChecker 9.4 has requirement requests<2.15,>=2.2, but you have requests 2.18.4.`

I'm running Debian Stable

    # pip -V
    pip 9.0.3 from /usr/local/lib/python2.7/dist-packages (python 2.7)

    # pip show LinkChecker
    Name: LinkChecker
    Version: 9.4
    Summary: check links in web documents or full websites
    Home-page: http://wummel.github.io/linkchecker/
    Author: Bastian Kleineidam
    Author-email: bastian.kleineidam@web.de
    License: GPL
    Location: /usr/local/lib/python2.7/dist-packages/LinkChecker-9.4-py2.7-linux-x86_64.egg
    Requires: dnspython, pyxdg, requests

LinkChecker was installed from the repo on GitHub.

**Comment by anarcat** [comment]
Debian stable has requests 2.12 - how did you end up in this situation? try `apt-get install python-requests`, that should solve the problem for you.

that restriction was necessary because of an incompatibility with newer requests/urllib versions (#76). work is still in progress upstream in that regard.

**Comment by SilkAndSlug** [comment]
> how did you end up in this situation?

No idea! Aptitude showed v2.12 as on-hold, with no versions installed.


> try `apt-get install python-requests`

Fixed it, thanks. I also ran `pip uninstall requests`.

**Comment by anarcat** [comment]
great! we may want to have an issue opened like this to make sure we update our requests compatibility layer, but until upstream is fixed, I am not sure we should bother too much...

**Comment by SilkAndSlug** [comment]
> how did you end up in this situation?

Apparently: via `pip list --outdated`. It listed requests v2.12, which my cronjob (via a bash script and pip) then upgraded to v2.18. 

I've used the above workaround, to silence the errors, but would appreciate a permanent fix (or "fix").
