### ISSUE TITLE
Getting Valid: 200 Ok when expecting Error: 500 

### ISSUE THREAD

**Issue by Prabh001** [linkchecker/linkchecker#150]
The site i'm testing is down today, unfortunately i can't provide the link here. However when ever i access that site with the command line tool the site redirects me to an error page but i still get a 200.

ex.
 URL        `http://link/blah/blah'
Real URL   http://link/blah/blah/System/Error
Check time 0.152 seconds
D/L time   0.000 seconds
Size       336B
Info       Redirected to `http://link/blah/blah/System/Error'.
Result     Valid: 200 OK

if it redirects me to a page like this i want it to give me the corresponding error. If i look at the actual link  in a web browser it looks like **" http;//link/blah/blah/System/Error/500 "**. is there any way i can tell the tool if it sees a link that looks like this to give me a 500 instead of a 200 (preferably something that can be used in shell scripting - bash)

**Comment by anarcat** [comment]
it will be really hard to help you out with an actual test case.

it's also quite unclear what you want... from what I understand, the site is giving linkchecker a `200` status code but you're somehow seeing a different status code some other way (how?) and you'd like linkchecker to *simulate* that error code (based on what?)

we'll definitely need more information here to help you out, sorry.

**Comment by anarcat** [comment]
is http://ctor-poc360:2114/System/Error really a 500 error? can you show me the output of `curl -I http://ctor-poc360:2114/System/Error`?

**Comment by Prabh001** [comment]
![image](https://user-images.githubusercontent.com/38537172/39256203-4ac57828-487c-11e8-8f64-4e1f29a9131e.png)

**Comment by anarcat** [comment]
that says "HTTP/1.1 200 OK". linkchecker is behaving correctly.

**Comment by Prabh001** [comment]
thanks, it seems like this is something on my side rather than linkchecker.
