### ISSUE TITLE
AttributeError: 'HttpUrl' object has no attribute 'proxy_type'

### ISSUE THREAD

**Issue by almontejt** [linkchecker/linkchecker#151]
I can't find a clear answer for this issue. Here is what I am getting from the command line: 

```
Traceback (most recent call last):
  File "linkcheck\director\checker.pyo", line 104, in check_url

Statistics:
Downloaded: 0B.
No statistics available since no URLs were checked.

That's it. 0 links in 0 URLs checked. 0 warnings found. 0 errors found.
S topped checking at 2018-05-01 15:17:18-004 (0.07 seconds)
   -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\director\checker.pyo", line 120, in check_url_data
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\director\checker.pyo", line 52, in check_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\director\checker.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 424, in check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\urlbase.pyo", line 442, in local_check
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\urlbase.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 128, in check_connection
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\checker\httpurl.pyo", line 66, in allows_robots
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\checker\httpurl.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 49, in allows_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\cache\robots_txt.py
    -- code not available --
  File "linkcheck\cache\robots_txt.pyo", line 62, in _allows_url
    -- couldn't find file, trying this instead: C:\Program Files (x86)\LinkChecker\library.zip\linkcheck\cache\robots_txt.py

    -- code not available --

AttributeError: 'HttpUrl' object has no attribute 'proxy_type'
System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.8 (default, Jun 30 2014, 16:03:49) [MSC v.1500 32 bit (Intel)] on win32
Requests: 2.2.1
Qt: 4.8.6 / PyQt: 4.11
Modules: QScintilla, Sqlite
Local time: 2018-05-01 15:17:18-004
```

**Comment by mgedmin** [comment]
I cannot see anywhere in git master where we would be trying to access an attribute `proxy_type`.  There's [one location](https://github.com/linkchecker/linkchecker/blob/268bf162c7bdead21f78c472e4c2635533df5cb9/linkcheck/cache/robots_txt.py#L61) where we're checking whether the attribute exists, and then we're accessing a different attribute called `proxytype`, which seems wrong to me, that's a different issue:


```python
        if hasattr(url_data, "proxy") and hasattr(url_data, "proxy_type"):
            kwargs["proxies"] = {url_data.proxytype: url_data.proxy}
```

Digging through git history reveals commits 52337f82cbc89c93929c16a8dd3eb0df60150300 and 4e56eceb358ae9e9c25833adbc44b761d321b586.  It looks like the first one fixed OP's issue, and the other one introduced the inconsistency while trying to fix [the same issue](https://github.com/wummel/linkchecker/issues/555), while also partially breaking the first fix.

I'm tempted to close this and open a new issue to resolve the proxy_type/proxytype naming mismatch.

**Comment by anarcat** [comment]
> I'm tempted to close this and open a new issue to resolve the proxy_type/proxytype naming mismatch.

seems reasonable.

@almontejt please try again with the latest version and reopen if the problem still occurs.

**Comment by mgedmin** [comment]
> I'm tempted to close this and open a new issue to resolve the proxy_type/proxytype naming mismatch

Here's the promised new issue: https://github.com/linkchecker/linkchecker/issues/152

**Comment by almontejt** [comment]
@anarcat @mgedmin Just to make sure, I would like to know how to use the latest version after I notified the issue related to the "proxy_type". Please let me know where should I look for this version since I'm already using version 9.3 from here: https://wummel.github.io/linkchecker/
