### ISSUE TITLE
HttpUrl.proxy_type vs HttpUrl.proxytype

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#152]
I think there's a bug in [RobotsTxt._allows_url()](https://github.com/linkchecker/linkchecker/blob/268bf162c7bdead21f78c472e4c2635533df5cb9/linkcheck/cache/robots_txt.py#L61):

```python
        if hasattr(url_data, "proxy") and hasattr(url_data, "proxy_type"):
            kwargs["proxies"] = {url_data.proxytype: url_data.proxy}
```

The hasattr() check looks for an attribute `proxy_type`, but then the code uses `proxytype`.
I think `proxytype` is correct, which means the if branch will never be taken and proxies will be ignored.
I also think the `hasattr()` checks are unnecessary -- they were added in a misguided attempt to fix an AttributeError for the misspelled `proxy_type` attribute.

If I'm right, user-visible effects of this bug are such that fetching /robots.txt for a site will ignore proxy settings.  (Unless those are configured in the session, in which case this bug has no user-visible effects at all?)

Why I think `proxytype` is correct: `git grep proxytype` shows multiple assignments and uses, whereas `git grep proxy_type` shows only this single `hasattr()` check.

Why I think `hasattr()` is unnecessary: `_allows_url()` is called from only one location (`allows_url()` in the same class), which unconditionally invokes `url_data.get_robots_txt_url()`, and `git grep get_robots_txt_url` shows that this method is defined only in one class, `HttpUrl`, which has `proxy` and `proxytype` attributes (they're accessed in `HttpUrl.get_request_kwargs` but are actually defined in the `ProxySupport` superclass).

It would be nice to have a unit test covering this part of the code, to prevent regressions and to make sure it's correct once fixed.

See https://github.com/linkchecker/linkchecker/issues/151#issuecomment-386018536 for background on how I stumbled upon this.

**Comment by mgedmin** [comment]
Basically the fix for this would be `git revert 4e56eceb358ae9e9c25833adbc44b761d321b586`, but I still want that unit test.

(I don't want to write it, though ;)

**Comment by mgedmin** [comment]
> If I'm right, user-visible effects of this bug are such that fetching /robots.txt for a site will ignore proxy settings. (Unless those are configured in the session, in which case this bug has no user-visible effects at all?)

AFAICT request session doesn't remember proxy information, so this is an actual bug.

**Comment by anarcat** [comment]
On 2018-05-02 21:44:14, Marius Gedminas wrote:
> Basically the fix for this would be `git revert 4e56eceb358ae9e9c25833adbc44b761d321b586`, but I still want that unit test.
>
> (I don't want to write it, though ;)

it'd be great if you could open a more specific issue about this,
otherwise maybe this one should be reopened?

**Comment by anarcat** [comment]
> it'd be great if you could open a more specific issue about this,
> otherwise maybe this one should be reopened?

gaah nevermind, the title looked the same so i thought you hadn't opened an issue. :/ sorry for the noise

**Comment by mgedmin** [comment]
Haha np ;)

**Comment by oupala** [comment]
As the fix has been identified by @mgedmin, I'd be happy to test a new release (or a test release) of linkchecker as this bug prevent me from using this great tool in my environment (where I do have proxies).

If one committer can apply the `git revert` command, it would be great!

**Comment by anarcat** [comment]
the problem was that we wanted a unit test first, and no one wants to write it. i feel uncomfortable just shooting from the hip randomly in the git history with the vague idea it might fix something (but break something else).

**Comment by oupala** [comment]
In my case, I'm technically not enough skilled to write a unit test (I don't know python).

If no one can write it (it may be hard to test a complex network solution that requires a proxy), we might imagine another solution: a dev branch that can be tested by people.

I would be able to test if a dev branch is working on my personal configuration.

What do you think of that?
