### ISSUE TITLE
HTML syntax check plugin error: 'ascii' codec can't encode character u'\u2026'

### ISSUE THREAD

**Issue by erichhuebner** [linkchecker/linkchecker#158]
```
> linkchecker -V
LinkChecker 9.4 released xx.xx.xxxx
Copyright (C) 2000-2014 Bastian Kleineidam
```

```
> locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Config file snippet:

```
_# Run W3C syntax checks
#[CssSyntaxCheck]
[HtmlSyntaxCheck]
```

With the HtmlSyntaxCheck plugin enabled many warning messages are outputted.  Seems like the system locale encoding isn't being used and is defaulting to ascii.  I grabbed a few functions from the linkcheck/i18n.py files, built a quick test script and the encoding is being set correctly, in that file at least.  The warnings mean that the HTML Syntax check failed, right?

```
100 threads active,  1161 links queued,  850 links in 105 URLs checked, runtime 1 minute, 6 seconds
WARNING 2018-06-11 16:39:40,553 CheckThread-https://pharmahub.org/search/ HTML syntax check plugin error: 'ascii' codec can't encode character u'\u2026' in position 1251: ordinal not in range(128) 
```

**Comment by cjmayo** [comment]
I've tried with current LinkChecker git and a non-ASCII page. I didn't get any errors. Makes sense that the change to Python 3 and BeautifulSoup has fixed this. Do open a new issue (with a minimal example) if there is still a problem.
