### ISSUE TITLE
Error: SSLError: hostname 'xxxx' doesn't match either of '*.one.com', 'one.com'

### ISSUE THREAD

**Issue by ajtruckle** [linkchecker/linkchecker#160]
When I run my site for link checking:

www.publictalksoftware.co.uk/help-msa/index.html

It comes up with lots of errors:  

>  Error: SSLError: hostname 'www.publictalksoftware.co.uk' doesn't match either of '*.one.com', 'one.com'

One.com is my domain provider. I am confused.

Andrew

**Comment by bcraigie** [comment]
Me too.  Seems like Linkchecker is doing a reverse lookup of the domain name to get the IP address, then looking that up, which will point to the web host so of course this error will occur

The error (or doing this check) seems to be pointless. :-)

**Comment by mgedmin** [comment]
Are you by any chance using an older version of Python 2 that didn't support SNI properly?

See http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors for more details

**Comment by ajtruckle** [comment]
I have no idea. I suimply run your software with my site help on my domain. Anything else is over my head. :)

**Comment by bcraigie** [comment]
I simply downloaded the exe file from http://wummel.github.io/linkchecker/dist/LinkChecker-9.3.exe so I don't know anything about Python.

**Comment by anarcat** [comment]
that is then very likely. i would say you are stuck as long as we don't have new builds for Windows, see #53...
