### ISSUE TITLE
document the Windows support status

### ISSUE THREAD

**Issue by OvaisAlam** [linkchecker/linkchecker#168]
Hello guys,
Under doc folder there's an installation guide. In that guide, for Windows, its written that we have to run the .exe file. 
Where's the .exe installation file for Windows in the project?

**Comment by oupala** [comment]
The [README](https://github.com/linkchecker/linkchecker/blob/master/README.rst) file say that:

> Windows builds are seriously lagging behind the Linux releases, see `#53 <https://github.com/linkchecker/linkchecker/issues/53>`_ for details. For now, the only two options are to install from source or use `Docker for Windows <https://www.docker.com/docker-windows>`_.

Have you seen that?

**Comment by OvaisAlam** [comment]
I missed that part.
Thank you for pointing out!

**Comment by anarcat** [comment]
why don't we use this as an opportunity to fix those docs? :)

**Comment by localhorst** [comment]
Can someone help iwth the "install from source" part? How do you do that for this repository?

**Comment by anarcat** [comment]
i changed the topic to reflect what we should do with this

**Comment by cjmayo** [comment]
https://github.com/linkchecker/linkchecker/blob/master/doc/install.txt has been updated with such newfangled things as the Microsoft Store and WSL. Do raise PRs with any additional info.
