### ISSUE TITLE
Internal errors report wrong issue-tracking url

### ISSUE THREAD

**Issue by figaw** [linkchecker/linkchecker#174]
## Summary

Wrong url in "Internal error"-output

## Steps to reproduce

 1. Provoke an internal error.

## Actual result

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

## Expected result

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
https://github.com/linkchecker/linkchecker/issues

## Environment
docker image, `linkchecker/linkchecker:latest`.

**Comment by anarcat** [comment]
raaah... looks like we still have some crap left in the code. :(
