### ISSUE TITLE
LinkChecker check-extern stalls - won't complete scan

### ISSUE THREAD

**Issue by regexaurus** [linkchecker/linkchecker#178]
## Summary
LinkChecker consistently stalls for a particular site I scan, when I check external links: 
```
linkchecker --𝐜𝐡𝐞𝐜𝐤-𝐞𝐱𝐭𝐞𝐫𝐧 -Fhtml/linkcheckerResults.html www.example.com
```
Typical output 🕥 😩 
```
7 threads active,     8 links queued, 12883 links in 13031 URLs checked, runtime 1 hour, 12 minutes
4 threads active,     0 links queued, 12901 links in 13038 URLs checked, runtime 1 hour, 12 minutes
1 thread active,     0 links queued, 12904 links in 13038 URLs checked, runtime 1 hour, 12 minutes
...
1 thread active,     0 links queued, 12904 links in 13038 URLs checked, runtime 10 hours, 15 minutes
1 thread active,     0 links queued, 12904 links in 13038 URLs checked, runtime 10 hours, 15 minutes
1 thread active,     0 links queued, 12904 links in 13038 URLs checked, runtime 10 hours, 15 minutes
```
At this point, my only recourse is to kill the scan. With a single CTRL+C, I see something like:
```
^CWARNING linkcheck.check 2018-08-07 12:12:42,653 MainThread interrupt; waiting for active threads to finish
WARNING linkcheck.check 2018-08-07 12:12:42,654 MainThread another interrupt will exit immediately
INFO linkcheck.check 2018-08-07 12:12:42,654 MainThread 1 URLs are still active. After a timeout of 5 minutes the active URLs will stop.
```
I have tried leaving a scan run for a few days with the same result. If I wait 5 minutes after the first CTRL+C:
```
WARNING linkcheck.check 2018-08-07 12:17:42,654 MainThread Abort timed out after 300 seconds, stopping application.
WARNING linkcheck.check 2018-08-07 12:17:42,654 MainThread user abort; force shutdown
```
It doesn't seem to always stall at the same place--always a different number of links checked (between scans) when the scan stalls. If I don't use _check-extern_ on this site, the scan completes normally. I use _check-extern_ on other sites where the scan completes normally.

## Steps to reproduce
Run linkchecker with _check-extern_ on a particular site.

## Actual result
LinkChecker eventually stalls and won't complete the scan normally.

## Expected result
LinkChecker should complete the scan normally.

## Environment
 * Operating system: 3.10.0-862.9.1.el7.x86_64 (CentOS 7.5.1804)
 * Linkchecker version: 9.4.0
 * Python version: 2.7.5
 * Install method: git

## Configuration file
Apparently my config file is default. The only uncommented lines were the section headers:

[output]
[text]
[gml]
[dot]
[csv]
[sql]
[html]
[blacklist]
[xml]
[gxml]
[sitemap]
[checking]
[filtering]
[authentication]

## Other notes

This is only a problem with one site I scan and not necessarily a linkchecker problem. If you have ideas/advice 💡 for debugging, I would appreciate it. 👏

**Comment by anarcat** [comment]
similar to #130 and #51, closing as dupe.
