### ISSUE TITLE
Cannot save 

### ISSUE THREAD

**Issue by ParkerD13** [linkchecker/linkchecker#184]
Hi, when I try to save a project or to save results from the windows gui, the file dialogue pops up but nothing happens when I click "save". No error or anything, I can only click abort. I tried different file formats and changed the file name. That all did not change anything.
I guess I have about 120 to 150 results on the list.
Linkchecker 9.3 on Win7 pro (Python 2.7.8, Requests 2.2.1, not the portable version).

**Comment by anarcat** [comment]
linkchecker-gui was split out in a separate repository, can you file this bug in this project instead? https://github.com/linkchecker/linkchecker-gui
