### ISSUE TITLE
Error: 403 Bad Behavior

### ISSUE THREAD

**Issue by fturco** [linkchecker/linkchecker#189]
## Summary

I'm trying to check my local HTML website before publishing it on the web.
It contains a link to https://earlyretirementextreme.com/, and I get the following error message from linkchecker:

```
URL        `https://earlyretirementextreme.com/'
Name       `Early Retirement Extreme'
Parent URL file:///home/fturco/repository/gitlab-fturco/fturco.gitlab.io/_site/now/index.html, line 29, col 19
Real URL   https://earlyretirementextreme.com/
Check time 4.995 seconds
Size       908B
Result     Error: 403 Bad Behavior
```

No error messages beside the previous one.

## Environment

My GNU/Linux distribution is Gentoo.
I'm using Linkchecker 9.3 (package `net-analyzer/linkchecker`)

## Configuration file

This is the contents of `/home/fturco/documenti/linkchecker/fturco.gitlab.io`:

```
[checking]
localwebroot=file:///home/fturco/repository/gitlab-fturco/fturco.gitlab.io/_site/
```

## Logs
[linkchecker.log](https://github.com/linkchecker/linkchecker/files/2364701/linkchecker.log)

I used the following command:

    linkchecker -f /home/fturco/documenti/linkchecker/fturco.gitlab.io \
    file:///home/fturco/repository/gitlab-fturco/fturco.gitlab.io/_site/ \
    --check-extern --verbose > linkchecker.log 2>&1

**Comment by anarcat** [comment]
checking https://earlyretirementextreme.com directly does not yield that error. so I'm not sure how to reproduce this... could you try to upgrade to the latest version and see if the problem still occurs?

**Comment by fturco** [comment]
I cannot reproduce this problem with `net-analyzer/linkchecker-9999` (Gentoo package for the latest git version). I didn't check linkchecker 9.4 because Gentoo doesn't provide a package for that yet.
