### ISSUE TITLE
Should support concurrent request limit per host

### ISSUE THREAD

**Issue by jikamens** [linkchecker/linkchecker#193]
LinkChecker should support not only specifying the maximum number of active threads overall, but more importantly the maximum number of concurrent requests for a single host. Otherwise you can overwhelm a single host with too many concurrent requests while requests for other hosts continue to work just fine.

(This is a real world problem, I just encountered it, not something theoretical.)

**Comment by cjmayo** [comment]
There is already:

maxrequestspersecond=NUMBER
    Limit the maximum number of requests per second to one host. The default is 10. Command line option: none

Not quite the same but can it fix the problem?

**Comment by jikamens** [comment]
I suppose so. :shrug:
