### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by astrofrog** [linkchecker/linkchecker#205]
## Summary

linkchecker crashes on Python 3.7

## Steps to reproduce

```
$ linkchecker http://www.google.com
Traceback (most recent call last):
  File "/Users/tom/python/dev/bin/linkchecker", line 36, in <module>
    from linkcheck.cmdline import print_version, print_usage, aggregate_url, \
  File "/Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/cmdline.py", line 23, in <module>
    from . import checker, fileutil, strformat, plugins
  File "/Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/checker/__init__.py", line 178, in <module>
    from . import (fileurl, unknownurl, ftpurl, httpurl, dnsurl,
  File "/Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/checker/ftpurl.py", line 29, in <module>
    from . import proxysupport, httpurl, internpaturl, get_index_html
  File "/Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/checker/httpurl.py", line 38, in <module>
    from ..HtmlParser import htmlsax
ImportError: dlopen(/Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/HtmlParser/htmlsax.cpython-37m-darwin.so, 2): Symbol not found: _PyString_AsString
  Referenced from: /Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/HtmlParser/htmlsax.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/tom/python/dev/lib/python3.7/site-packages/linkcheck/HtmlParser/htmlsax.cpython-37m-darwin.so
```

## Environment

 * Operating system: Darwin eleven-9.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
 * Linkchecker version: 9fed3800973d7b94b9c295e2d3423b0b276fe7a8 (latest dev as of time of reporting)
 * Python version: Python 3.7.1
 * Install method: ``pip install git+https://github.com/linkchecker/linkchecker.git``
 * Site URL: google.com

## Configuration file

None

**Comment by anarcat** [comment]
raaah that html parser again!

**Comment by anarcat** [comment]
actually, now that I think about it - we don't actually support Python 3 at all... see #40 ...

**Comment by iranzo** [comment]
Based on the lifecycle of python it would be good get this rolling

**Comment by mgedmin** [comment]
January 2020 will definitely light a fire under our posteriors!

@cjmayo has been bravely pushing forward Python 3 support in https://github.com/linkchecker/linkchecker/pull/210 (which is not a real PR, so ignore the merge conflicts; it's more of a tracking bug for a bunch of smaller PRs). 

I think we're currently stuck on https://github.com/linkchecker/linkchecker/pull/230 where nobody's sure what's the right thing to do...

**Comment by anarcat** [comment]
linkchecker will be removed from the next debian release if we don't fix this in time (which will take a few months/year still, of course). see [bug #936950](https://bugs.debian.org/936950).

**Comment by anarcat** [comment]
it seems we'll also need to remove a dependency if we really want to fix python3 support, see #268

**Comment by cjmayo** [comment]
#337 is the new place to follow Python 3 support.

**Comment by SchoolGuy** [comment]
@mgedmin Can we somehow push that PR #337 is merged. This project was just removed from tumbleweed because it isn't Py3 compatible. I would like to see it again in there! I would offer to help but I think most of the work is done already if you could get the 9 (!) open PR's into master.

**Comment by mgedmin** [comment]
Yeah, it's 2020, and I withdraw any objections to dropping Python 2.7 support.

**Comment by cjmayo** [comment]
> Yeah, it's 2020, and I withdraw any objections to dropping Python 2.7 support.

That's one down. The other is the quoting everything in UTF-8.

(#337 does need a rebase on master, and some updates from the review comments)

**Comment by SchoolGuy** [comment]
@cjmayo I can do it if you want. That should in theory only be a repetitive task which isn't hard to do.

**Comment by cjmayo** [comment]
Thanks but it is the deciding whether to always quote in UTF-8 that is the blocker, not pushing the commits.

**Comment by hydrapolic** [comment]
Linux Gentoo is trying to get rid of Python2 only packages - https://bugs.gentoo.org/712958. Please, what are the plans to migrate this to Python3? If it's not in reasonable time I'm afraid we'll have to drop it from Linux Gentoo :(

**Comment by SchoolGuy** [comment]
We (openSUSE) had already to remove the package. I will put it in there again if there is activity and I would invest some time to help porting it further to Py3.

**Comment by anarcat** [comment]
> I will put it in there again if there is activity and I would invest some time to help porting it further to Py3.

There was a *lot* of work put into porting linkchecker. We just need help for one last little push.

**Comment by hydrapolic** [comment]
Can you please be more specific what exactly needs to be done?

**Comment by mgedmin** [comment]
> Can you please be more specific what exactly needs to be done?

This is basically _why_ the port is unfinished: we're not exactly sure.

I think @cjmayo knows best.  #337 is probably the next step?  I see that the tests are green, so why don't we merge it and see what happens?  There were some open questions about handling non-ASCII characters in URLs and possibly behaving differently from browsers, but we can fix that up afterwards.

There's one merge conflict in tox.ini, but I hope it won't be too hard to resolve.

**Comment by anarcat** [comment]
> Can you please be more specific what exactly needs to be done?

What @mgedmin said. But on top of that, i would add that someone could probably "just" try to merge that BS4 branch locally and *just run with it*: try it in python3 and see what happens. Then we'd probably need some patch to get Travis to test on py3 as well...

But we're preeetty close, I'd say...

**Comment by cjmayo** [comment]
Everything is visible, the responses to the last time the question was asked in January immediately before are the summary of current status and there is more detail on #337.

I guess we are indeed at the point were we just merge the current approach and hope for the best. But first #337 does need a tidy up as mentioned there (OK the actual commits to do that aren't visible, I have them locally) , give me a few days (my available time a the moment is being spent on issues elsewhere arising from retiring Python 3.6) - that's also a warning that #337 will get rebased (master has moved on since) so do raise any objections soon.

@anarcat you committed Python 3 testing into master 2 years ago https://github.com/linkchecker/linkchecker/commit/4382215a75b6eb56f4e4866b4b3c6e8849468b8a but commits to master are allowed to fail, on #337 failures are not allowed https://github.com/linkchecker/linkchecker/pull/337/commits/90c7f5993b9fb326ad4c45813ab774d23731952a.

**Comment by anarcat** [comment]
@cjmayo thanks for replacing my poor brain, you're awsome. :) and thanks again for your extraordinary work, can't wait to see what you give us next!

:tada:

**Comment by mimi89999** [comment]
Linkchecker was removed from Debian testing: https://tracker.debian.org/news/1086810/linkchecker-removed-from-testing/

**Comment by hydrapolic** [comment]
Just testing the latest git master with python 3.8 and seems to be working ok ;)

**Comment by mgedmin** [comment]
I think we can close this?  git master supports Python 3 and only Python 3.

**Comment by dfkotz** [comment]
I just installed linkchecker and this bug occurred immediately - just typing 'linkchecker' at command line, or 'linkchecker --help', triggers the crash.

```
[MacOS:~/projects/web]$ linkchecker --help
Traceback (most recent call last):
  File "/usr/local/bin/linkchecker", line 36, in <module>
    from linkcheck.cmdline import print_version, print_usage, aggregate_url, \
  File "/usr/local/lib/python3.7/site-packages/linkcheck/cmdline.py", line 23, in <module>
    from . import checker, fileutil, strformat, plugins
  File "/usr/local/lib/python3.7/site-packages/linkcheck/checker/__init__.py", line 178, in <module>
    from . import (fileurl, unknownurl, ftpurl, httpurl, dnsurl,
  File "/usr/local/lib/python3.7/site-packages/linkcheck/checker/ftpurl.py", line 29, in <module>
    from . import proxysupport, httpurl, internpaturl, get_index_html
  File "/usr/local/lib/python3.7/site-packages/linkcheck/checker/httpurl.py", line 38, in <module>
    from ..HtmlParser import htmlsax
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/linkcheck/HtmlParser/htmlsax.cpython-37m-darwin.so, 2): Symbol not found: _PyString_AsString
  Referenced from: /usr/local/lib/python3.7/site-packages/linkcheck/HtmlParser/htmlsax.cpython-37m-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.7/site-packages/linkcheck/HtmlParser/htmlsax.cpython-37m-darwin.so
[MacOS:~/projects/web]$ python3 --version
Python 3.7.7
```

**Comment by dfkotz** [comment]
MacOS 10.14.6 (18G4032)

```
[MacOS:~/projects/web]$ pip3 check linkchecker
No broken requirements found.
[MacOS:~/projects/web]$ pip3 install --upgrade linkchecker
Requirement already up-to-date: linkchecker in /usr/local/lib/python3.7/site-packages (9.4.0)
Requirement already satisfied, skipping upgrade: dnspython in /usr/local/lib/python3.7/site-packages (from linkchecker) (1.16.0)
Requirement already satisfied, skipping upgrade: requests<2.15,>=2.2 in /usr/local/lib/python3.7/site-packages (from linkchecker) (2.5.1)
Requirement already satisfied, skipping upgrade: pyxdg in /usr/local/lib/python3.7/site-packages (from linkchecker) (0.26)
```

**Comment by mgedmin** [comment]
> Requirement already up-to-date: linkchecker in /usr/local/lib/python3.7/site-packages (9.4.0)

9.4.0 does not support Python 3.  Only git master supports Python 3.

We're planning to release a new version soon: #359

**Comment by dfkotz** [comment]
Thank you.  I look forward to it.

On May 20, 2020, at 5:58 PM, Marius Gedminas <notifications@github.com<mailto:notifications@github.com>> wrote:



Requirement already up-to-date: linkchecker in /usr/local/lib/python3.7/site-packages (9.4.0)

9.4.0 does not support Python 3. Only git master supports Python 3.

We're planning to release a new version soon: #359<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinkchecker%2Flinkchecker%2Fissues%2F359&data=02%7C01%7CDavid.F.Kotz%40Dartmouth.edu%7C648423c9ecd74909b5b808d7fcd69985%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637255870951880786&sdata=bbKVS3LouS2SxNHwc41BP4e%2FL10pkdLx%2BC%2FEtGAwOCo%3D&reserved=0>

**Comment by dfkotz** [comment]
Looks like it’s still not out…

On May 20, 2020, at 5:58 PM, Marius Gedminas <notifications@github.com<mailto:notifications@github.com>> wrote:



Requirement already up-to-date: linkchecker in /usr/local/lib/python3.7/site-packages (9.4.0)

9.4.0 does not support Python 3. Only git master supports Python 3.

We're planning to release a new version soon: #359<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flinkchecker%2Flinkchecker%2Fissues%2F359&data=02%7C01%7CDavid.F.Kotz%40Dartmouth.edu%7C648423c9ecd74909b5b808d7fcd69985%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637255870951880786&sdata=bbKVS3LouS2SxNHwc41BP4e%2FL10pkdLx%2BC%2FEtGAwOCo%3D&reserved=0>
