### ISSUE TITLE
HTML attributes :str, :href errorneously checked

### ISSUE THREAD

**Issue by strohel** [linkchecker/linkchecker#209]
## Summary

Some JavaScript frameworks (Vue) use special :src :href HTML attributes with arbitrary content. Linkchecker seems to treat :src, :href as if they were real src, href, falsely checking them.

Tag Examples:
`<img :src="'//static.goout.net/logos/partners/cs/' + logo" alt="logo" class="logo-img"/>`
`<a :href="'/ticketing/sale/' + currentSaleId"></a>`

Page examples:
https://goout.net/cs/pro-poradatele-divadla/
https://goout.net/cs/listky/zvrhla-margaret/ybge/

## Steps to reproduce

 1. Check on of the example pages above

## Actual result

Broken link `'/ticketing/sale/' + currentSaleId` reported.

## Expected result

No broken links reported.

## Environment

 * Operating system: Gentoo Linux
 * Linkchecker version: LinkChecker 9.4.0
 * Python version: Python 3.6.5
 * Install method: Gentoo ebuild
 * Site URL: https://goout.net/cs/pro-poradatele-divadla/

**Comment by cjmayo** [comment]
I've tried this and it looks fixed in git to me.
There is a Gentoo ebuild in development if that is you preference:
https://github.com/gentoo/gentoo/pull/16900
