### ISSUE TITLE
linkchecker gives 'Permission denied' error

### ISSUE THREAD

**Issue by sarcanon** [linkchecker/linkchecker#237]
## Summary

On start-up, linkchecker coughs up a "Permission denied" error and aborts. Exact error message is: `ksh: linkchecker: Permission denied`

## Steps to reproduce

Any set of parameters produces same error, even something as simple as this:
   `linkchecker --version`

## Environment

 * Operating system: OpenBSD 6.5-current (snapshot dated 13 April 2019)
 * Linkchecker version: Not entirely sure, since I can't check. But the app was installed as a package, labeled as version 9.3p3
 * Python version: Machine has three versions of python installed: 2.7.16, 3.5.3, 3.6.8p0
 * Install method: package linkchecker-9.3p3
 * Site URL: Would seem to be irrelevant.

## Configuration file

None.

## Logs

None produced.

## Other notes

Haven't the foggiest idea.

**Comment by mgedmin** [comment]
Can you provide the following information please

- the output of `which linkchecker`
- the output of `head $(which linkchecker)`

**Comment by sarcanon** [comment]
Thank you for your reply.

```
# which linkchecker
/usr/local/bin/linkchecker
```
And:
```
# head $(which linkchecker)
#!/usr/local/bin/python2.7 -Ru
# -*- coding: iso-8859-1 -*-
# Copyright (C) 2000-2014 Bastian Kleineidam
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
#
```

**Comment by mgedmin** [comment]
Thank you!  Now, if you run `/usr/local/bin/python2.7 -c 'print "hello"'`, does that print hello or fail with a Permission denied error?

**Comment by sarcanon** [comment]
Well, as you probably expected, it says the following:
```
# /usr/local/bin/python2.7 -c 'print "hello"'
ksh: /usr/local/bin/python2.7: Permission denied
#
```
Having determined that, it appears python runs afoul of OpenBSD's restrictions on W^X-violating programs, a feature introduced in OpenBSD 6.0 and documented here: [https://www.openbsd.org/faq/upgrade60.html](https://www.openbsd.org/faq/upgrade60.html).

If you add "wxallowed" as an option in /etc/fstab to the appropriate partition (in my case, /usr/local), and reboot, then python (and other python-dependent applications such as linkchecker) will run correctly.

Thank you @mgedmin for the assistance and pointing out the source of the problem.

**Comment by mgedmin** [comment]
You're welcome!
