### ISSUE TITLE
help wanted please - ignore= filetypes

### ISSUE THREAD

**Issue by b0br2019** [linkchecker/linkchecker#241]
Summary

Hello, just started using this today - awesome stuff. Like the dot format and making a graphviz (^_^)

I'm trying to exclude urls with ignore, images css js but cant seem to get it right.. tried all the below; anyone point me in the right direction please?

##################### filtering options ##########################
[filtering]
ignore=.*(?:png|jpg|css|jpeg|gif|tiff|bmp|svg|js|pdf)$ 
ignore-url=.*(?:png|jpg|css|jpeg|gif|tiff|bmp|svg|js|pdf)$ 
ignore=(http(s?):)|([/|.|\w|\s])*\.(?:png|jpg|css|jpeg|gif|tiff|bmp|svg|js|pdf)
ignore='(png|jpg|css|jpeg|gif|tiff|bmp|svg|js)$'
ignore everything with 'lconline' in the URL name
Iconline
and ignore everything with 'bookmark' in the URL name
  bookmark
 and ignore all mailto: URLs
  ^mailto:
  start
  index.php
  .jpg
  .png
ignore= 
   lconline 
   bookmark 
    a comment 
   ^mailto:  
   php$
   jpg$
   png$
   pdf$
   css$
   js$
   '.php$'
   '.css$'

**Comment by b0br2019** [comment]
now tried these too; no luck - anyone know how to not include certain filetypes in url list please?

ignore= 
	.*\css
	.*\.(css|pdf|js(own)?|jpg?)$
	(r'^.*?[.](?P<ext>min\.css|min\.js|\w+)$')
	('['*.jpg']')
	('['*.png']')
	('['*.pdf']')
	('['*.css']')
	('['*.js']')
	('['*.min.js']')
	('['*.min.css']')
ignore-url= 
	.*\css
	.*\.(css|pdf|js(own)?|jpg?)$
	(r'^.*?[.](?P<ext>min\.css|min\.js|\w+)$')
	('['*.jpg']')
	('['*.png']')
	('['*.pdf']')
	('['*.css']')
	('['*.js']')
	('['*.min.js']')
	('['*.min.css']')
  
# do not recurse into the following URLs

nofollow=
	.*\css
	.*\.(css|pdf|js(own)?|jpg?)$

**Comment by mgedmin** [comment]
(I would help if I knew how, but I've never used any of the filtering options.)

**Comment by alekspog** [comment]
It seems to me you should use --no-follow-url parameter.

**Comment by cjmayo** [comment]
Looks like a lack of indentation issue, from the linkcheckerrc man page:


***MULTILINE***
Some option values can span multiple lines. Each line has to be indented for that to work. Lines starting with a hash (#) will be ignored, though they must still be indented.
```
ignore=
  lconline
  bookmark
  # a comment
  ^mailto:
```
