### ISSUE TITLE
http server cannot be used as a https proxy

### ISSUE THREAD

**Issue by pes-soft** [linkchecker/linkchecker#258]
## Summary

Linkchecker does not pass proxy for HTTPS connections, even when `https_proxy` environment variable is present. LC shows that proxy is detected and configured, but actual connections go directly (being block by firewall in my case). It seems that applying proxy in [httpurl.py#L248](https://github.com/linkchecker/linkchecker/blob/ecba4e7ac861d45d6afb2366e5607b9d2b857b38/linkcheck/checker/httpurl.py#L248) is not passing the correct proxy type. When I replace `self.proxytype` with `"https"` the connections work well via HTTPS ( maybe there should be self.scheme used? - sorry didn't analyze further ).

## Steps to reproduce

 1. export https_proxy=http://myproxy:8080
 2. linkchecker https://www.my-website.com

## Actual result
Connection does not use proxy and fails.

## Expected result
Connection uses proxy and succeeds.

## Environment
 
 * Operating system: `CentOS 7 Linux iuwejsdfjiasjd 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
 * Linkchecker version: `LinkChecker 9.4.0`
 * Python version: `Python 2.7.5`
 * Install method: `pip install from git on Apr 29, 2019 10:33:07 AM`
 * Site URL: No public site

## Configuration file

No configuration file

**Comment by c-markwell** [comment]
Thanks pes-soft!

Changing:
	kwargs["proxies"] = {self.proxytype: self.proxy}
To:
	kwargs["proxies"] = {self.scheme: self.proxy}
in get_request_kwargs in checker/httpurl.py fixed it for me too.

Using "self.proxytype" refers to the scheme (http, https etc) of the connection to the proxy server, whereas "self.scheme" refers to the scheme of the link being checked.

LinkChecker uses the Python "requests" library to download pages, which needs a map of protocol to proxy settings, e.g:
{
  'http': 'http://proxy.example.org:3128',
  'https': 'http://proxy.example.org:1080',
}

So if you're checking a https URL and have https_proxy set to a proxy server that uses http (as pes-soft and I am), the map key is wrongly set to "http", which the requests library doesn't use, as it's looking for a proxy to use with the https protocol (the protocol of the page to be checked).

**Comment by mgedmin** [comment]
Would you like to submit a pull request with this fix?

**Comment by cjmayo** [comment]
I've proposed a solution in the PR #589.

I haven't got a proxy server, testing of the PR by someone who is using one would be helpful.

**Comment by cjmayo** [comment]
Fixed by removing all the proxy code from LinkChecker - Requests will handle proxies for us.
This does mean the limited support for ftp_proxy has gone. As has reading the HTTP proxy setting (HTTPS was never read) from GNOME and KDE - however, from experimentation I see that Fedora 35 and Ubuntu 20.04 are setting the *_proxy environment variables when you use their GUI's to configure proxies. Users of other OS's with KDE & GNOME who are configuring proxies through their GUI's might want to check http_proxy is set (e.g. `printenv http_proxy`). Kubuntu 20.04 did not in my tests.

**Comment by alfador1** [comment]
This still doesn't work. I can reproduce it with 10.1.0 version
