### ISSUE TITLE
Release 9.4 on PyPI

### ISSUE THREAD

**Issue by danmichaelo** [linkchecker/linkchecker#261]
Seems like [9.4 has been released](https://github.com/linkchecker/linkchecker/releases/tag/v9.4.0), but not on PyPI:

https://pypi.org/project/LinkChecker/#history

**Comment by mgedmin** [comment]
The original maintainer is missing in action, and none of us have permissions to make PyPI releases.  See #4, which is tracking this problem.

**Comment by mgedmin** [comment]
(BTW thank you for filing this issue, it gave me just enough motivation to nudge the process along by filing https://github.com/pypa/warehouse/issues/6136)
