### ISSUE TITLE
Docker Hub Image is Out of Date

### ISSUE THREAD

**Issue by SoreGums** [linkchecker/linkchecker#264]
#135 	

everything might have been fine - it's not fine anymore :)

https://hub.docker.com/r/linkchecker/linkchecker/builds

The Dockerfile in the repo is legit A+

The Dockerfile used for the currently hosted image is F-

Be sweet if an automated build could be configured.
I'm SoreGums on DockerHub if that'll help get it moving

**Comment by SoreGums** [comment]
rightio - https://microbadger.com/images/soregums/linkchecker

probs better to switch to Debian buster-slim base image and install the package and tag the image as 9.4.0 - will keep plugging away at automating that over the next few days. as long as tags are debian/x should be able to automate it.

as for master or a dev image - probably just have to live with giant images...

**Comment by anarcat** [comment]
it seems my account was disconnected from Docker hub. Maybe I did this after the recent compromise, in panic mode, and forgot to reset it.

I just did, and it should build again, but I can't help but feel that granting Docker Hub access to my GitHub is the wrong way to do things, so I'll dig a little further.

**Comment by anarcat** [comment]
so it seems the relink triggered a build that updated the docker image, so the immediate problem is fixed. uncomfortable with granting Docker Hub access to my GitHub account, however, I have disconnected it again. Hopefully the webhook that remains will still work, but it's possible this will require further thought. When the next thing gets merged, we'll see.

**Comment by SoreGums** [comment]
neat - the image that builds master is fine for running master - this 40mb one though is ideal for running the release version. i'll tinker with it as mentioned

**Comment by anarcat** [comment]
@SoreGums any improvements are welcome as PRs, of course. Thanks for the heads up!

**Comment by kostis-codefresh** [comment]
@anarcat we can do it the other way around. Have github actions push the image to Dockerhub. So Dockerhub credentials are inserted in the Github account and not the other way around.

Would you accept such as PR?

**Comment by anarcat** [comment]
> @anarcat we can do it the other way around. Have github actions push the image to Dockerhub. So Dockerhub credentials are inserted in the Github account and not the other way around.

lesser evil, i guess?

> Would you accept such as PR?

are you asking me to publicly store my Docker credentials inside GitHub? :)

**Comment by kostis-codefresh** [comment]
@anarcat just wanted to note that in both cases (dockerhub and Github) you can use a token for authentication instead of the actual password. So you can revoke that token at will at any point afterwards.

**Comment by cjmayo** [comment]
As far as I can see (without having used one) a Docker access token cannot do admin tasks [1] but it can still manage the content, and belongs to an individual user account. An enterprise can have policies in place and ensure there is someone around to spot the need for and do the revocation. Our resources are a bit more limited.

There is another option now: GitHub Packages Container registry [2].

Home Assistant is using this for example [3].

I've prepared a workflow (mainly copy and paste...) #573

Thoughts?

[1] https://docs.docker.com/docker-hub/access-tokens/
[2] https://github.blog/2021-06-21-github-packages-container-registry-generally-available/
[3] https://github.com/home-assistant/core/pkgs/container/home-assistant

**Comment by cjmayo** [comment]
OK, no need to try Home Assistant we now have:
https://github.com/linkchecker/linkchecker/pkgs/container/linkchecker

Bit of checking (feedback welcome), and maybe tweaking then we can update the README.

**Comment by cjmayo** [comment]
Tweaked in PR #576.

**Comment by cjmayo** [comment]
Now live, rolling tag changed from master to latest, plus git checksum tags.

**Comment by oupala** [comment]
It should be made clearer that the Docker image of linkchecker is available on GitHub registry, as this registry is not widely known.

It took me a while to understand that the Docker image was hosted by GitHub, I was looking at DockerHub and I was seing that the image had not been updated for many years...

**Comment by cjmayo** [comment]
I've proposed a few extra words for the README in #582.
