### ISSUE TITLE
hung in docker after 20min

### ISSUE THREAD

**Issue by fatum-rok** [linkchecker/linkchecker#265]
hello.

I start 
`docker run --rm -it -u "$(id -u):$(id -g)" -v "$PWD/mnt:/mnt" linkchecker/linkchecker      --user-agent='Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'      --no-robots      --verbose      --check-extern      -t 10      --ignore-url=".*selcdn.net.*"       -F "csv//mnt/auto-plus.ru.csv" "https://auto-plus.ru"`
several times. 

Always it stops output logs after some time (20 min - 1 hour). 
After hunging ctrl+c don't interrupt execution. Only `docker stop` can help. 
In htop i see python processes, 2 of it consume 100% cpu each.

**Comment by mgedmin** [comment]
Can you install [py-spy](https://github.com/benfred/py-spy) and use `py-spy --dump --pid NNN` to get the stack traces of the hung linkchecker processes/threads?

Also it would be helpful to know what version of linkchecker you're running.

**Comment by fatum-rok** [comment]
I was try latest versionfrom docker hub and build image from last repo version (from master). got same result.

py-spy dump in attachment
[spy.txt](https://github.com/linkchecker/linkchecker/files/3489200/spy.txt)

**Comment by cjmayo** [comment]
The Docker Hub images are using LinkChecker 9.

We now have new images at GitHub based on the latest code.
https://github.com/linkchecker/linkchecker/pkgs/container/linkchecker

Feel free to open a new issue if you have problems with the new images.
