### ISSUE TITLE
When to wait for binary files for Windows?

### ISSUE THREAD

**Issue by mrkaban** [linkchecker/linkchecker#266]
Earlier, you suggested that I change the links on my site from "wummel / linkchecker" to yours, but for a year and a half, I still did not see binary files for Windows. This means that 100% of my audience will not be able to run the program simply by clicking download and installing.

"wummel / linkchecker" is mousy, but anyone can install it.

therefore, the initial project has 1186 stars, and you have 209.

PS: You promised to release binary files soon, a year and a half has passed.

**Comment by mgedmin** [comment]
To put it plainly: we could use some help.

So far we haven't even managed to get a Linux release out (blocked on PyPI admins, see #4).

**Comment by anarcat** [comment]
> "wummel / linkchecker" is mousy, but anyone can install it.

What's great about free software is that just works too. You can install the outdated, unmaintained, and probably insecure (more than ours, that is) version of linkchecker that still runs on windows, and that no one knows how to rebuild.

That's great!

But what we're trying to do here is create a community of people that can keep on making this stuff work. Me and @mgedmin and others have been trying our best with very limited resources to keep this project alive, against all odds. So pushing us around and complaining about delays is not helping.

I'm not sure we promised anything, to anyone. I certainly didn't promise anything, at least. If someone wants to contribute and publish those binaries, go right ahead, we'd be very happy to get some help.

But in the meantime, we don't have a scheduled release date for windows binaries. As @mgedmin said, we're already struggling to do normal Python releases so I'd rather focus on that (and the bs4 removal, which will make windows installs easier, possibly) than battle an architecture I don't know.

There are at least two other issues regarding windows support in the queue (#168 #53 #267), so I'm going to close this ticket and hope we'll move on over there.
