### ISSUE TITLE
--config -> "parts=base" not works

### ISSUE THREAD

**Issue by RoDiSVK** [linkchecker/linkchecker#28]
Hi, if you set the configuration 
--config=./test.lcp

[csv]
parts=parentname,url,infostring,**base**

then **base** item be ignored

"parts=all" is without **base** too

thanks

**Comment by mgedmin** [comment]
It would be helpful if you could tell us what output you expected and what output you got instead.  And, also, what input we could use to reproduce this.

**Comment by RoDiSVK** [comment]
If I am using

parts=all
OR
parts=parentname,url,infostring,result,warningstring,baseref,valid,line,column,dltime,size,checktime,cached,level,modified,**base**

**base** is ignored

```
# created by LinkChecker at 2017-02-05 22:48:33+002
# Get the newest version at http://wummel.github.io/linkchecker/
# Write comments and bugs to https://github.com/wummel/linkchecker/issues
# Support this project at http://wummel.github.io/linkchecker/donations.html
urlname;parentname;baseref;result;warningstring;infostring;valid;url;line;column;name;dltime;size;checktime;cached;level;modified
```

expected...

a href=xyz return base=a
link href=xyz return base=link
img src=xyz return base=img
script src=xyz return base=script

**Comment by cjmayo** [comment]
> parts=parentname,url,infostring,result,warningstring,baseref,valid,line,column,dltime,size,checktime,cached,level,modified,**base**
> 
> **base** is ignored
> 

Yes, it was coded as baseref in the CSV logger.

> expected...
> 
> a href=xyz return base=a
> link href=xyz return base=link
> img src=xyz return base=img
> script src=xyz return base=script

No, this is solely for the `<base>` element [1] and logs its href.

I've created #472 which I think fixes this.

[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
