### ISSUE TITLE
changelog doesn't mention 9.4 release date

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#322]
According to GitHub, the 9.4 release [exists](https://github.com/linkchecker/linkchecker/releases/tag/v9.4.0), but [`doc/changelog.txt`](https://github.com/linkchecker/linkchecker/blob/master/doc/changelog.txt) doesn't have a codename for it, nor a release date.

It might also be a good idea to compare the list of features/changes/fixes with the one [published on github](https://github.com/linkchecker/linkchecker/releases/tag/v9.4.0), to make sure it's complete.

**Comment by mgedmin** [comment]
@anarcat I can do this, but I'd like to focus on the rest of `get_content()` calls from https://github.com/linkchecker/linkchecker/issues/317#issuecomment-544536320 so maybe you'd like to volunteer for this? ;)

**Comment by anarcat** [comment]
> @anarcat I can do this, but I'd like to focus on the rest of get_content() calls from #317 (comment) so maybe you'd like to volunteer for this? ;)

sorry, i'm barely keeping up with the flood of reviews. ;)

**Comment by anarcat** [comment]
> @anarcat I can do this, but I'd like to focus on the rest of get_content() calls from #317 (comment) so maybe you'd like to volunteer for this? ;)

sorry, i'm barely keeping up with the flood of reviews. ;)

if/when we do fix this, also update `doc/development.mdwn` to make sure we don't make this mistake again.

**Comment by mgedmin** [comment]
Looks like https://github.com/linkchecker/linkchecker/blob/master/doc/development.mdwn#release-process mentions the changelog update now.
