### ISSUE TITLE
Review get_content() calls for possible type issues

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#323]
In the comments of bug #317 I've asked for a review of all `url_data.get_content()` calls to see if there are any other bugs introduced by the change in 5fc01455b7e2707509accaa58a586f7d1dc41443 that made it return unicode instead of bytes.

This is a tracking bug for that review:

- [x] linkcheck/checker/fileurl.py:            self.content_type = mimeutil.guess_mimetype(self.url, read=self.get_content)
- [x] linkcheck/checker/ftpurl.py:        self.content_type = mimeutil.guess_mimetype(self.url, read=self.get_content)
- [x] linkcheck/checker/httpurl.py:            parser.feed(self.get_content()) → https://github.com/linkchecker/linkchecker/pull/325
- [x] linkcheck/checker/httpurl.py:            rtype = mimeutil.guess_mimetype_read(self.get_content)
- [x] linkcheck/parser/\_\_init__.py:    for url, name, lineno in parse_bookmark_data(url_data.get_content()):
- [x] linkcheck/parser/\_\_init__.py:    for url, name in parse_bookmark_data(url_data.get_content()):
- [x] linkcheck/parser/\_\_init__.py:    for line in url_data.get_content().splitlines():
- [x] linkcheck/parser/\_\_init__.py:    for line in strip_comments(url_data.get_content()).splitlines():
- [x] linkcheck/parser/\_\_init__.py:    for mo in linkfinder(url_data.get_content()):
- [x] linkcheck/parser/sitemap.py:        data = url_data.get_content() → https://github.com/linkchecker/linkchecker/pull/330
- [x] linkcheck/plugins/markdowncheck.py:        content = url_data.get_content()
- [x] linkcheck/plugins/parsepdf.py:        data = url_data.get_content() → https://github.com/linkchecker/linkchecker/pull/324
- [x] linkcheck/plugins/parseword.py:        content = url_data.get_content() → https://github.com/linkchecker/linkchecker/pull/326
- [x] linkcheck/plugins/regexcheck.py:        content = url_data.get_content()
- [x] linkcheck/plugins/viruscheck.py:        data = url_data.get_content() → https://github.com/linkchecker/linkchecker/pull/329

**Comment by mgedmin** [comment]
`mimeutil.guess_mimetype(read=self.get_content)` passes the `read` parameter to `mimeutils.guess_mimetype_read()` for a bunch of plaintext, HTML and XML mime types, which in turn does a bunch of regex searches using pure ASCII regexes with no control chars in them.  Should be safe.

**Comment by mgedmin** [comment]
`HttpUrl.content_allows_robots()` tries to feed the result of `get_content()` into the HTML parser, which is known to be a problem.  This happens only when `self.is_html()` returns True.  The purpose of this is to parse `<meta name="robots" content="...">` tags.

Two tests tickle this code:
- tests/checker/test_http.py::TestHttp::test_html
- tests/checker/test_http_redirect.py::TestHttpRedirect::test_redirect

I think they don't fail because all the files they're parsing are pure ASCII.

**Comment by cjmayo** [comment]
For linkcheck/plugins/parsepdf.py see #324 - it did need fixing, the test wasn't being run in Travis because the pdfminer dependency was not being installed.

**Comment by mgedmin** [comment]
parse_bookmark_data() passes the thing to json.loads(), which happily accepts Unicode.

**Comment by mgedmin** [comment]
parse_text(): can parse unicode fine, assuming url_data.add_url() accepts unicode URLs.  (Which is a safe assumption, I think, given that bookmark parsers pass unicode URLs to the same function.)

**Comment by mgedmin** [comment]
parse_css(): is fine with unicode.

**Comment by mgedmin** [comment]
parse_swf(): uses regular expression to find URLs.  In SWF files, apparently.  Which I thought were binary?  Oh boy.

Anyway, there's a test for this and it fails if I add a stray `raise 'BOO'` into parse_swf(), so I think we're good.

**Comment by mgedmin** [comment]
sitemap parser: feeds the data to xml.parsers.expat.  Dunno if that one wants bytes or strings.  No test fails if I add a `raise 'BOO'` in the code, which is not good.

The [docs for xml.parses.expat](https://docs.python.org/2/library/pyexpat.html) contain this lovely warning:
> Warning: The pyexpat module is not secure against maliciously constructed data. If you need to parse untrusted or unauthenticated data see XML vulnerabilities.

Experiments show that expat is Unhappy if I feed unicode strings to it.

**Comment by mgedmin** [comment]
There's a sitemap xml file in the test data directory, but it's only to test that the mime type guesser recognizes it.

I can't find any place that calls parse_sitemap() or parse_sitemapindex(), but I'm sure it's happening here:
https://github.com/linkchecker/linkchecker/blob/bbb90eba81d85d060837d1cbd82a1ff72a4f93bf/linkcheck/parser/__init__.py#L41-L46

**Comment by mgedmin** [comment]
Markdown parser: uses regexes, which is fine, and then it uses `str_text.maketrans()`, which I think means not only we can use unicode, but we *must* use unicode, or things will break.

This code is tested (tests/checker/test_file.py::TestFile::test_markdown).

**Comment by mgedmin** [comment]
Word parser: talks to a an actual instance of WORD.EXE via some Microsoft cross-process communication thing (win32com).

Word files are binary and decoding them to unicode is a bad idea.  This cannot be tested on Linux, so I'll make an untested patch.

**Comment by mgedmin** [comment]
Regex check: deals with text files, is find with unicode.

**Comment by mgedmin** [comment]
viruscheck: content is fed to a socket.sendall(), therefore it should be bytes.

There are tests, but they are conditionally skipped.  Maybe we could install clamav-daemon in Travis CI and see if the test will run?  I've tried this locally, and it sort of works (the test file signature has changed, so one test fails; PR incoming).

It looks like the tests cover the actual scanning API, but not the feeding URL data into the scanner parts.  Who cares about plumbing, amirite?

**Comment by anarcat** [comment]
no idea, but you rock. :)

**Comment by mgedmin** [comment]
Ok, I've reviewed all the code, and I absolutely 100% guarantee that I may or may not have found at least some lurking bugs.  All of which (those I've found) have their own PRs open, so I'm going to close this meta-issue.
