### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#327]
## Summary

When I run the tests (using tox), I see the following warning:

```
linkcheck/checker/ftpurl.py:140
  /home/mg/src/linkchecker/linkcheck/checker/ftpurl.py:140: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
    if self.filename in files:
```

**Comment by anarcat** [comment]
filenames are tricky. they are not necessarily unicode in UNIX, and should probably be treated as bytes only, except on display.

**Comment by anarcat** [comment]
should we care about FTP at all if we can't find a server to test this with?

**Comment by mgedmin** [comment]
Well, if an actual end-user bug report comes in complaining about FTP, that would definitely raise the priority of this bug.

**Comment by mgedmin** [comment]
I think this has been fixed during the Python 3 rewrite.
