### ISSUE TITLE
No 'app' makefile

### ISSUE THREAD

**Issue by joeBwanKenobi** [linkchecker/linkchecker#340]
## Summary
I have followed the mac OSX manual installation instructions successfully up to step #7. 
--use-mirrors has been deprecated, so this throws an error.  Removing the option successfully installs requirements.  However, the next step 'make app' results in an error message "make: *** No rule to make target `app'.  Stop."

I have tried 'make Makefile' which returns "make: Nothing to be done for `Makefile'."
## Environment

 * Operating system: Darwin Kernel Version 17.7.0, Mac OS High Sierra 10.13.6
 * Linkchecker version: 9.3, but haven't successfully installed
 * Python version: Python 2.7.16
 * Install method: from source, git clone git@github.com:linkchecker/linkchecker.git linkchecker

**Comment by xdebbie** [comment]
I have the same issue!

**Comment by mgedmin** [comment]
The original maintainer is missing in action.  I don't think any of the new maintainers own a Mac, so our ability to help with this OS is limited.

Perhaps try `pip install --user linkchecer`?  Or, if you want a newer Python 3 compatible version from git master that doesn't need a C compiler, try `pip3 install -user .` in a git checkout.

**Comment by xdebbie** [comment]
When I try `pip install --user linkchecker`, I get as a result:

```
Requirement already satisfied: linkchecker in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (9.4.0)
Requirement already satisfied: requests<2.15,>=2.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from linkchecker) (2.14.2)
Requirement already satisfied: dnspython in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from linkchecker) (1.16.0)
Requirement already satisfied: pyxdg in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from linkchecker) (0.26)
```

Then if I try `pip3 install --user linkchecker`

I get the same result
```
Requirement already satisfied: linkchecker in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (9.4.0)
Requirement already satisfied: requests<2.15,>=2.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from linkchecker) (2.14.2)
Requirement already satisfied: dnspython in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from linkchecker) (1.16.0)
Requirement already satisfied: pyxdg in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from linkchecker) (0.26)
```

Then when I try `make app`, the outcome is:

```
This program requires Python 3.5 or later.
This program requires Python 3.5 or later.
This program requires Python 3.5 or later.
This program requires Python 3.5 or later.
make: *** No rule to make target `app'.  Stop.
```

My Python version is 3.7.7...

**Comment by mgedmin** [comment]
"Requirement already satisfied" means you already have it installed, system-wide.  Does it work?

9.4.0 doesn't support Python 3, I'm surprised you have it installed successfully in Python 3.8.... oh, we don't do the usual post-release addition of `.dev0` to our setup.py metadata after cutting a release, so git master identifies itself as 9.4.0.  That is very confusing, let me open a PR about this.

**Comment by xdebbie** [comment]
No it does not work... but it is weird it requires Python 3.5+ if you say that the 9.4.0 does not support Python 3... 

The `make app` does not work at all so it does not create a dmg installation file

Thank you though, I hope a solution comes by at some point, it would be really nice if it ever works on OSx

**Comment by mgedmin** [comment]
9.4.0 does not support Python 3.  git master supports Python 3.  Confusingly, we forgot to increment the version number in setup.py while we were working on the Python 3 port, so git master identifies itself as 9.4.0.  I've filed #39 to fix that.

I think what you have is not 9.4.0, but a git snapshot.

I did not expect `make app` to start working after you do a pip install.  I expected pip install to create a linkchecker script in ~/.local/bin or wherever pip install --user installs scripts on Mac OS.  If your goal is to have a .dmg (which I gather is an application packaging thingy for Mac OS), then somebody who knows about application development on Mac OS needs to create a pull request fixing `make app`...

(Or somebody could buy me a Macbook and I might look into it.  But probably not.)

**Comment by cjmayo** [comment]
`make app` was removed some time ago:
e3ab9024 ("Remove platform-specific installer stuff and ensure a build .whl wheel file can be built.", 2016-01-17)

`pip` is the recommended method, e.g.
`pip3 install git+https://github.com/linkchecker/linkchecker.git`
