### ISSUE TITLE
CentOS 7 - help with install

### ISSUE THREAD

**Issue by atomGit** [linkchecker/linkchecker#342]
i would really like to get this running on a CentOS VPS, but i'm not yet very comfortable with Linux

the install instructions in the readme don't work for me - there is no python-pip package (it's python3-pip) and it all goes downhill from there :)

rather than installing pip to install linkchecker, can i install/build from source and, if so, how would i do so?

**Comment by cjmayo** [comment]
`python3-pip` sounds good.

The recommended method is:
`pip3 install git+https://github.com/linkchecker/linkchecker.git`

pip will do everything for you - do give it a go!
