### ISSUE TITLE
Unable to check links behind password-protected URL 

### ISSUE THREAD

**Issue by this-guy-commits** [linkchecker/linkchecker#343]
## Summary

I am new to linkchecker and may be missing something but I didn't see any other issues related to mine so here goes. I want to check the links behind a password-protected site that has a single password prompt at render. Once I enter my password, the page I want to test loads. 

My understanding of linkchecker is that if I want to check links behind a password-protected site, I am to modify the linkcheckerrc file found at `config/linkcheckerrc/` and include the CGI name for the password field and then provide the actual string I want to pass into the said field. 

## Steps to reproduce

 1. Modify `linkcheckerrc` `loginuserfield` and `loginpasswordfield` fields with my expected values (e.g loginuserfield="password" and loginpasswordfield="super_secret_pass")
2. Run linkchecker via `linkchecker --config ./config/linkcheckerrc <URL to check>`
3. Linkchecker will auth for me and parse password protected sites link's

## Actual result
Linkchecker does not appear to authenticate with the site I expected it to (I confirm this by seeing the presence of links only found as part of the password prompt page) 

## Expected result
Linkchecker would authenticate with the site and check all links behind the password prompt

## Environment
LinkChecker 9.4.0 released xx.xx.xxxx

 * Operating system: iOS Mojave
 * Linkchecker version: 9.4.0
 * Python version: 3.7.4
 * Install method: From source TarBall
 * Site URL: n/a

## Configuration file

[linkcheckerrc.txt](https://github.com/linkchecker/linkchecker/files/4093496/linkcheckerrc.txt)

## Notes

I know the config file is being loaded correctly as I set verbose output to on via `verbose=1` and I no longer have to specify `-v` via the CLI to observe verbose output.

**Comment by cjmayo** [comment]
To try to be clear:
```
loginuserfield="password"
loginpasswordfield="super_secret_pass"
```
should work for a login form like:
```html
<form action="/log_me_in">
<input name="password">
<input name="super_secret_pass">
</form>
```
Is that what you have?

**Comment by StanKatsyuk** [comment]
@cjmayo my page doesn't actually have a username field. The initial landing page has a password field (it's a Dev server). 

Would your example still work?

**Comment by cjmayo** [comment]
Linkchecker version: 9.4.0
Python version: 3.7.4
Install method: From source TarBall

Is that actually Python 2.7? On 21 Jan even master would not have worked with Python 3.

In theory a password only form would use ("password" is the default so doesn't need setting in linkcheckerrc):

```
loginpasswordfield="password"
```
to match:
```html
<form action="/log_me_in">
<input name="password">
</form>
```
You would then get prompted for the password when you run linkchecker (or use `-p`).

However, it looks like Linkchecker will always send both username and password:

https://github.com/linkchecker/linkchecker/blob/d80a075372dadd5cff2fe772c220464748704f1b/linkcheck/director/aggregator.py#L94-L99

Maybe your server doesn't like that?

If you want to experiment with that code then great. N.B. we are just finishing the last bit of the Python 3 transition so master is still going to see a fair number of commits in the coming week or so (I think I have made master definitely only work with username and password with 48b590cf8b, so this is an interesting report!).

**Comment by cjmayo** [comment]
> If you want to experiment with that code then great.

Perhaps the place to start would be testing the response, or maybe just adding `response.raise_for_status()`.

**Comment by cjmayo** [comment]
Thinking about it some more, with just a password this:

https://github.com/linkchecker/linkchecker/blob/d80a075372dadd5cff2fe772c220464748704f1b/linkcheck/director/aggregator.py#L94

would then likely cause an exception because the form.data dictionary keys are the input element name attributes found in the form. That would make me happy with my change because that would result in a log message (although maybe it should be a warn and not a debug) rather than a crash.

**Comment by StanKatsyuk** [comment]
Would this still allow me to provide only a password field or are you
saying the exception being raised would log a message but it wouldn't sign
into the login page?

The logic for my Dev server is:

1. You are first redirected to a login page where you enter a password
2. A valid password entry then redirects you into the page.

Thank you again for all your work and help with this,

**Comment by cjmayo** [comment]
Probably easier to start from the top and describe what is supported. All configuration mentioned are entries in the authentication section of linkcheckerrc
https://linkchecker.github.io/linkchecker/man5/linkcheckerrc.5.html#lbAG

Both username and password fields are required, in a form of a page at an address configured in `loginurl` of the type:

```html
<form action="/log_me_in">
<input name="login">
<input name="password">
</form>
```
"login" can be configured in loginuserfield, "password" in loginpasswordfield.

The page "/log_me_in" must set cookies.

Turning to your case. Hopefully the redirection turns out not to matter, the page you want to check needs to be addressable, and that is the address you pass to the linkchecker command.
If that is true then to use linkchecker I think your easiest route would be to add a `<input name="login">` to the form on the login page. Else it would mean hacking your own copy of linkchecker (or ideally develop generic support for password only login forms) with line 94 above being a place to start, and that would need adding to with the next release of linkchecker.

So, this has been useful, it prompted me to write some commits with more error checking (still both username and password required) that I'm waiting to submit now.

**Comment by StanKatsyuk** [comment]
Great, thanks for your help. Il try what you proposed and report back
tomorrow.

**Comment by StanKatsyukCT** [comment]
@cjmayo sorry for the late reply. 

So the HTML for the password field on my site is: 
`<div id="login-fields">
                    
<div id="password-field" class="field">
            <div class="input ltr">
                        <div class="passwordwrapper"><input type="password" id="password" class="text password fullwidth" name="password" autocomplete="off" placeholder="Password"></div>
            </div>
            </div>


    </div>`

I added the following to my configuration file: 

```
##################### password authentication ##########################
[authentication]
# WARNING: if you store passwords in this configuration entry, make sure the
# configuration file is not readable by other users.
# Different user/password pairs for different URLs can be provided.
# Entries are a triple (URL regular expression, username, password),
# separated by whitespace.
# If the regular expression matches, the given user/password pair is used
# for authentication. The commandline options -u,-p match every link
# and therefore override the entries given here. The first match wins.
# At the moment, authentication is used for http[s] and ftp links.
#entry=
# Note that passwords are optional. If any passwords are stored here,
# this file should not readable by other users.
#  ^https?://www\.example\.com/~calvin/ calvin mypass
#  ^ftp://www\.example\.com/secret/ calvin

# if the website requires a login the URL and optionally the user and
# password CGI fieldnames can be provided.
loginurl=https://my_website_url/who-is-there
# The name of the user and password CGI field
loginuserfield=login
loginpasswordfield=password
# Optionally any additional CGI name/value pairs. Note that the default
# values are submitted automatically.
#loginextrafields=
password:my_secret_password
#  name2:value 2
```

However I still can't get it to auth past the password prompt. 

As a summary: 
1. My login page doesn't have a username field, just a "password" field and a "submit" button


I wonder if I need to use some other tool like selenium to get past it? 

Thanks in advance,

**Comment by cjmayo** [comment]
For linkchecker to be able to log in the password `<input>` needs to be part of a `<form>` with an action that does the submission.

It's not in your HTML snippet but I'm guessing in this case the submit button is using JavaScript to send the password. That won't work with linkchecker.

**Comment by cjmayo** [comment]
If it is a `<form>` with an action, then the latest linchecker is required to support password only forms:
`pip3 install git+https://github.com/linkchecker/linkchecker.git`

**Comment by cjmayo** [comment]
I believe the form usage is now fixed in git.

Do open a new issue for any problems with that, or a separate clear feature request for something else (although a PR would likely be more successful!).
