### ISSUE TITLE
linkchecker 10.0.0 release

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#359]
We should make a new major release. Now that PyPI is unblocked (#4), we can push new releases to all our platforms and this is going to become urgent with the Python 2 deprecation, so that we can ship our python3 code (#205).

Anything else we *must* ship in this release? I guess this will block on at least #4 and #205, but is there anything else?

I think it should be called 10.something because it will definitely include significant API changes, if only Python3, but there are also changes to the linkchecker API itself (whatever that is).

Do we want to do a release candidate first?

I would propose we ship 10.0.0rc1 as soon as #4 and #205 are done, what do others think?

**Comment by mgedmin** [comment]
> I would propose we ship 10.0.0rc1 as soon as #4 and #205 are done, what do others think?

:+1:

**Comment by cjmayo** [comment]
Yes.

Other things that don't work:
- MS Windows (haven't tried but at least one point in the code)
- meliae #268

Hopefully we might get some interest in fixing Windows, there is #267. There is also an open attempt at CI #129. From my point of view we could ship with those still unresolved.

I've had a start at documentation updates #362.

**Comment by mgedmin** [comment]
AFAIU #267 was about building the C extension code, which we no longer have in git master.  So yay!

If we want to care about Windows, we ought to add appveyor integration → see https://github.com/linkchecker/linkchecker/pull/127.

**Comment by SchoolGuy** [comment]
Just my two cents: As soon as 10.0.0 is out again, I can submit it into openSUSE Tumbleweed and then back to openSUSE Leap 15.2 maybe. If desired I could try to setup an automatic build of the package in OBS with your help. These build artifacts are not publishable (to my knowledge) then as a restriction (protect the user from possible malicious code etc, etc).

**Comment by hydrapolic** [comment]
+1 for a new release, I'll add to Gentoo Linux with python3 only support.

**Comment by mgedmin** [comment]
> I would propose we ship 10.0.0rc1 as soon as #4 and #205 are done, what do others think?

Both are closed now, time for 10.0.0rc1?

**Comment by cjmayo** [comment]
I wouldn't object as long as we commit to an rc2. I am still working through my backlog of tidy ups and I think they would help the maintainability of 10.

I think I have found some edge case crashers, (forgotten what they are now) that I haven't yet written any fixes for. But it does now seem to be working for several people, and there is obviously some demand!

N.B. documentation updates in #362 to mention 10rc1 and provide install and upgrade information.

**Comment by mgedmin** [comment]
In that case let's not call it `rc1` but rather 10.0.0.a1.

**Comment by cjmayo** [comment]
> In that case let's not call it `rc1` but rather 10.0.0.a1.

OK by me.

**Comment by hydrapolic** [comment]
For starters you can just tag the current master with 10.0.0 - it's enough for us to create a new version in Gentoo Linux. Later, you can tag 10.0.1, 10.0.2 ... and create a release if you wish. It's a good starting point for users to test it.

**Comment by anarcat** [comment]
> In that case let's not call it `rc1` but rather 10.0.0.a1.

:+1:

and for the record, i'm all for "release any time". the more often we release, the easier it will get, as we will find (and fix) various warts in the process and documentation.

**Comment by mgedmin** [comment]
I've created a 10.0.0 milestone in GitHub and added some issues we want to fix before making the 10.0.0 final release.

**Comment by mgedmin** [comment]
I don't have any more bugs targeted for 10.0.0.

(By "bugs" I mean actual bugs in the code, not github issues about documentation and release process.  There are plenty of those, and they seem harder than code fixes.)

**Comment by anarcat** [comment]
:shipit:

**Comment by cjmayo** [comment]
I don't have any more work in progress.

**Comment by themr0c** [comment]
What are the necessary actions to proceed to the release?

**Comment by mgedmin** [comment]
An active maintainer would be nice.  I'm burned out; anarcat is burned out.

I think I have sufficient GitHub and PyPI rights to produce a release, if I knew what exactly needs to be done.  Figuring out the release steps is the hard part.

(They're probably documented in some file in this repository.  But then I'd have to review them to make sure they're not outdated.)

@cjmayo, do you want PyPI rights to upload Linkchecker releases?  Tell me your PyPI username and you'll have them,

**Comment by cjmayo** [comment]
> An active maintainer would be nice. I'm burned out; anarcat is burned out.
> 
Likewise, I can't justify spending more time on this for now, and I think releases are overrated in this case, but bumping 9.4 from PyPI does appeal.

The release I propose would be a minimal change to master, #527.

> 
> @cjmayo, do you want PyPI rights to upload Linkchecker releases? Tell me your PyPI username and you'll have them,

OK, I'll give it a go -  my PyPI username is the same as GitHub.

**Comment by themr0c** [comment]
Sadly, my python skills are too low to become a good maintainer.

**Comment by mgedmin** [comment]
> OK, I'll give it a go - my PyPI username is the same as GitHub.

You should have a PyPI invitation in your inbox.

**Comment by cjmayo** [comment]
> Sadly, my python skills are too low to become a good maintainer.

Well, prompting the release is definitely something.

**Comment by cjmayo** [comment]
> You should have a PyPI invitation in your inbox.

And I've used it... I think everything has worked.

**Comment by anarcat** [comment]
someone still needs to update the debian package in debian before the freeze. i'll pen it down and hope to have time to deal with it, otherwise: i'm sorry. ;) if i fail, someone can always ask for a sponsor ... e.g. https://mentors.debian.net/

**Comment by hydrapolic** [comment]
Many thanks for tagging and releasing, adding to Gentoo Linux.

**Comment by anarcat** [comment]
note that i uploaded a repackaged thing into Debian. it may be a little rough and i found a few problems with the upstream source (#530 and #529), but it should otherwise make it to the next stable release (bullseye)! phew!

i have also uploaded the debian branch to the debian-specific git repo at <https://salsa.debian.org/python-team/packages/linkchecker> i think we might want to delete the `debian` branch here to avoid any confusion and let the debian people manage that stuff on their own... it's now out of sync, for what that's worth.
