### ISSUE TITLE
Erroneous log message claiming access has been denied by robots.txt

### ISSUE THREAD

**Issue by carinedengler** [linkchecker/linkchecker#368]
## Summary

When trying to check URL behind HTTP authentication without providing user authentication and the --verbose flag, the log message erroneously claims that access has been denied by robots.txt. This is somewhat confusing, especially since this message is shown even if no robots.txt exists.

Thanks for your help!

## Steps to reproduce

 1.  use linkcheckerrc to check URL behind HTTP authentication with the --verbose flag without providing user authentication

## Actual result

Log message claims that access has been denied by robots.txt even if none is present ("Access denied by robots.txt, checked only syntax.").

## Expected result

Log message indicating that no user authentication has been provided (e.g. "401 Unauthorized, checked only syntax.").

## Environment

 * Operating system: Debian GNU/Linux 10 (buster)
 * Linkchecker version: LinkChecker 9.4.0
 * Python version: Python 2.7.16
 * Install method: distribution package

## Logs
linkchecker http://example.com --verbose
INFO linkcheck.cmdline 2020-04-20 09:23:52,433 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2020-04-20 09:23:52+002

URL        `http://example.com'
Real URL   http://example.com
Check time 0.062 seconds
Info       Access denied by robots.txt, checked only syntax.
Result     Valid: syntax OK

Statistics:
Downloaded: 0B.
Content types: 0 image, 0 text, 0 video, 0 audio, 1 application, 0 mail and 0 other.
URL lengths: min=32, max=32, avg=32.

That's it. 1 link in 1 URL checked. 0 warnings found. 0 errors found.
Stopped checking at 2020-04-20 09:23:52+002 (0.12 seconds)

**Comment by cjmayo** [comment]
It's a timely report because from recently looking at the code it seemed there was a lack of error messages in this area which could cause confusion. #364 has some extra checking which should mean the next release is better at this.

I haven't tried but the changes to linkcheck/director/aggregator.py in
https://github.com/linkchecker/linkchecker/commit/710af274c75ac5eb4cb41b10fca32a20176dd478#diff-8052feb855b642708f4e8554e7d176c8

might apply to 9.4.0, even just the `response.raise_for_status()` may be enough depending on your setup.

**Comment by carinedengler** [comment]
OK, I'll look into it. Thanks for your reply!

**Comment by cjmayo** [comment]
I believe this is fixed in git. Do raise a new issue with any problems.
