### ISSUE TITLE
GIT clone not working on OSx

### ISSUE THREAD

**Issue by xdebbie** [linkchecker/linkchecker#389]
Is there anything wrong with this link? Every time I try to clone the git using this: 

`git clone git@github.com:linkchecker/linkchecker.git linkchecker`

it returns me this:

```
Cloning into 'linkchecker'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any tips on how to get around this issue?

**Comment by mgedmin** [comment]
Try `git clone https://github.com/linkchecker/linkchecker`.

**Comment by xdebbie** [comment]
That worked, thank you!

**Comment by anarcat** [comment]
this is a documentation wart in install.txt, will fix.
