### ISSUE TITLE
Proxy code review

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#431]
While reviewing #430 I'm looking at the linkchecker code that deals with proxies, and I thought it might be useful to record some of my observations:

- [ ] ProxySupport.set_proxy restricts proxy URLs to http: or https: because urllib2 doesn't support anything else:

 
 https://github.com/linkchecker/linkchecker/blob/152dbeb9b886adf9bd71265460325c7781985e95/linkcheck/checker/proxysupport.py#L40-L45

  But we're not using urllib2, we're using requests, and requests also [supports socks5: and socks5h: schemes](https://requests.readthedocs.io/en/master/user/advanced/#socks).  We could remove this restriction and gain socks proxy support!

- [ ] ProxySupport.proxyauth is assigned twice and never used.  Requests supports proxy authentication directly by extracting the username and password from the proxy URL.

https://github.com/linkchecker/linkchecker/blob/152dbeb9b886adf9bd71265460325c7781985e95/linkcheck/checker/proxysupport.py#L35

https://github.com/linkchecker/linkchecker/blob/152dbeb9b886adf9bd71265460325c7781985e95/linkcheck/checker/proxysupport.py#L57-L61

This code could be removed.

- [ ] ProxySupport.ignore_proxy_host is calling urllib.request.proxy_bypass, which always checks the no_proxy environment variable, plus some system-specific other proxy bypass lists on Windows and MacOS.  Then ProxySupport.ignore_proxy_host checks the no_proxy environment variable again.  Why?

https://github.com/linkchecker/linkchecker/blob/152dbeb9b886adf9bd71265460325c7781985e95/linkcheck/checker/proxysupport.py#L63-L73

The [commit](https://github.com/linkchecker/linkchecker/commit/e6f43b6822343f1625e78db07c9d5bd4875b3c93) message says "Fixed the no_proxy handling", and the changelog entry added in that commit says "Honor the no_proxy environment variable".  It was using urllib.proxy_bypass back then (2009).  That function in Python 2.7 also already checked the no_proxy environment variable.  What am I missing?

- [ ] Configuration.sanitize_proxies checks for http proxy and for ftp proxy, but does nothing about https proxy.
https://github.com/linkchecker/linkchecker/blob/152dbeb9b886adf9bd71265460325c7781985e95/linkcheck/configuration/__init__.py#L325-L337

GNOME at least has separate https proxy configuration in gsettings.  This may be relevant to PR #420.

- [ ] ProxySupport.get_netloc appears to be dead code, never called from anywhere.
https://github.com/linkchecker/linkchecker/blob/152dbeb9b886adf9bd71265460325c7781985e95/linkcheck/checker/proxysupport.py#L75-L89

It can be removed

**Comment by vyshnavarajesh** [comment]
can you please share the commnad to run linkchecker using proxy
