### ISSUE TITLE
Cannot install on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by mdykierek** [linkchecker/linkchecker#435]
## Steps to reproduce
Try to follow the install instructions. 

## Actual result
Fail
## Expected result
Succes
## Environment
Ubuntu 20.04 LTS for amd64

**Comment by mdykierek** [comment]
If I understand your answer correctly linkchecker won't be available on Debian and Ubuntu until it is re-written for python3?
I may be of course wrong, but isn't Python2 dead as of January 1st 2020? This may be one of reasons for Debian and Canonical decided to go with Python3.
Is there any plan and/or estimate for the re-write?

**Comment by anarcat** [comment]
> If I understand your answer correctly linkchecker won't be available on Debian and Ubuntu until it is re-written for python3?

Well, what I am saying is that this is Debian and Ubuntu's call, not ours.

>  I may be of course wrong, but isn't Python2 dead as of January 1st 2020? This may be one of reasons for Debian and Canonical decided to go with Python3.

That is correct.

>  Is there any plan and/or estimate for the re-write?

Yes, see #40, #205 and many others.

>  So I guess this "bug" should be considered as one of request for update...

The current situation is that the port is largely complete and we just need to sit down and actually do a release.

**Comment by mdykierek** [comment]
That's a good news then. Thanks for your time.

**Comment by reinierpost** [comment]
Having updated my systems from Ubuntu 18.04 to 20.04,

- I would really appreciate having an Ubuntu 20.04 and 22.04 package for `linkchecker` (I like Ubuntu's `unattended-upgrades`)
- `python` is still Python 2.7, but `python3` is there, too, and is 3.8, so the package could be made
- `pip3 install linkchecker` gives me a fully operational `linkchecker` in `$HOME/.local/bin/linkchecker`, so the package isn't needed to get a linkchecker in a single command

**Comment by anarcat** [comment]
> * I would really appreciate having an Ubuntu 20.04 and 22.04 package for `linkchecker` (I like Ubuntu's `unattended-upgrades`)

there are no 20.04 packages but there *are* 22.04 packages, as far as I can tell here:

https://packages.ubuntu.com/jammy/linkchecker

am i missing anything?
 
> * `python` is still Python 2.7, but `python3` is there, too, and is 3.8, so the package could be made

the package is there and should work properly.

> * `pip3 install linkchecker` gives me a fully operational `linkchecker` in `$HOME/.local/bin/linkchecker`, so the package isn't needed to get a linkchecker in a single command

great!
