### ISSUE TITLE
Docker: this version of runc doesn't work on cgroups v2: unknown.

### ISSUE THREAD

**Issue by dwreski** [linkchecker/linkchecker#456]
## Summary

Attempting to run the "docker run" command provided, to run linkchecker in a docker container, it fails with:
docker: Error response from daemon: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown.

Docker command fails to complete successfully.

## Steps to reproduce

 1. Run the "docker run" command provided in the documentation
 2. 
 3. 

## Actual result
# docker run --rm -it -u $(id -u):$(id -g) linkchecker/linkchecker --verbose https://example.com
Unable to find image 'linkchecker/linkchecker:latest' locally
latest: Pulling from linkchecker/linkchecker
5ae19949497e: Pull complete 
ed3d96a2798e: Pull complete 
f12136850781: Pull complete 
1a9ad5d5550b: Pull complete 
6f18049a0455: Pull complete 
900d7861659d: Pull complete 
536c9e631831: Pull complete 
26bb094a8db8: Pull complete 
d7d14a785fe2: Pull complete 
385eea7e1287: Pull complete 
Digest: sha256:2a0e4489e0f042abd7594a14fdfdd181dccd5bd700f16dfce70301e5cc174e49
Status: Downloaded newer image for linkchecker/linkchecker:latest
docker: Error response from daemon: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown.

## Environment

 * Operating system: 
# uname -a
Linux sage.inside.example.com 5.7.6-201.fc32.x86_64 #1 SMP Mon Jun 29 15:15:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 * Linkchecker version: 
I don't want to install it locally, but use the docker version first.

 * Python version: 
Python 3.8.3

 * Install method: 
I'd like to run it from docker.

 * Site URL:

**Comment by cjmayo** [comment]
Does running other docker images work on that system?

**Comment by cjmayo** [comment]
I don't think this is a LinkChecker problem. If you disagree do reopen with more information.
