### ISSUE TITLE
Debian package has unsatisfiable dependencies

### ISSUE THREAD

**Issue by erickoledadevrel** [linkchecker/linkchecker#457]
As per the [Debian tracker](https://tracker.debian.org/pkg/linkchecker), the linkchecker package is blocked from migrating into Debian's testing distribution due to unsatisfiable dependencies. My company requires that packages migrate to the testing distribution before they are available on corporate devices, so I am unable to install this package.

**Comment by anarcat** [comment]
i suggest you file this ticket against Debian.

also, if your company (is that Google??) depends on linkchecker for its work, how about contributing to this project a little? :)

**Comment by erickoledadevrel** [comment]
I'm not that familiar with what I'm reading on the Debian tracker, but I believe the problem is with this package's dependencies, not their infrastructure. We were recommending some of our authors use linkchecker to check their websites, but we've since migrated to other tooling. This was more of a courtesy, since it seems like it's been broken in Debian for a few months and there was no existing tracking bug.

**Comment by anarcat** [comment]
> I'm not that familiar with what I'm reading on the Debian tracker, but I believe the problem is with this package's dependencies, not their infrastructure. 

The problem is that Someone (ie. probably me) needs to upload a new release of Linkchecker, which supports Python 3, in Debian.

> We were recommending some of our authors use linkchecker to check their websites, but we've since migrated to other tooling. This was more of a courtesy, since it seems like it's been broken in Debian for a few months and there was no existing tracking bug.

I am already painfully aware of the state of Linkchecker (and my other python2 packages)  in Debian, thanks. :/
