### ISSUE TITLE
Limit of 100001 for URLs

### ISSUE THREAD

**Issue by MircoPerini** [linkchecker/linkchecker#463]
## Summary
The total URLs has a limit of **100001**, reached this limit the value remains unchanged even if the scan proceeds and "_links queued_" and "_links checked_" reach values of millions of units:

100 threads active, 30673 links queued, 68486 links in 99903 URLs checked, runtime 2 hours, 43 minutes
100 threads active, 30698 links queued, 68541 links in 99984 URLs checked, runtime 2 hours, 43 minutes
100 threads active, 30720 links queued, 68636 links in **100001** URLs checked, runtime 2 hours, 43 minutes
100 threads active, 30748 links queued, 68706 links in **100001** URLs checked, runtime 2 hours, 43 minutes
100 threads active, 30776 links queued, 68776 links in **100001** URLs checked, runtime 2 hours, 43 minutes
100 threads active, 30800 links queued, 68836 links in **100001** URLs checked, runtime 2 hours, 44 minutes
[...]
100 threads active, 168972 links queued, 223066 links in **100001** URLs checked, runtime 7 hours, 1 minute
100 threads active, 169039 links queued, 223083 links in **100001** URLs checked, runtime 7 hours, 1 minute
[...]
100 threads active, 2489377 links queued, 1461870 links in **100001** URLs checked, runtime 1 day, 12 hours, 21 minutes
100 threads active, 2489509 links queued, 1461942 links in **100001** URLs checked, runtime 1 day, 12 hours, 21 minutes

This bug is independent of the number of threads, occurs with either 1, 10, 100 or 1000

1 thread active, 2836180 links queued, 1576480 links in **100001** URLs checked, runtime 5 days, 23 hours, 6 minutes
10 threads active, 5415569 links queued, 3007833 links in **100001** URLs checked, runtime 3 days, 8 hours, 27 minutes
100 threads active, 2489509 links queued, 1461942 links in **100001** URLs checked, runtime 1 day, 12 hours, 21 minutes
1000 threads active, 688499 links queued, 629969 links in **100001** URLs checked, runtime 23 hours, 47 minutes

## Steps to reproduce

 1. Run linkchecker on a site with more than 100001 URLs

## Actual result

10 threads active, 5415569 links queued, 3007833 links in **100001** URLs checked, runtime 3 days, 8 hours, 27 minutes

## Expected result

something like:
10 threads active, 5415569 links queued, 3007833 links in **8423402** URLs checked, runtime 3 days, 8 hours, 27 minutes

## Environment

 * Operating system:
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:	6.10
Codename:	Santiago
 * Linkchecker version: 
WARNING linkcheck.check 2020-07-29 12:39:48,165 MainThread Running as root user; dropping privileges by changing user to nobody.
LinkChecker 10.0.0.dev0 released xx.xx.xxxx
Copyright (C) 2000-2014 Bastian Kleineidam
 * Python version: Python 3.6.3
 * Install method: 
pip install --verbose --upgrade https://github.com/linkchecker/linkchecker/archive/master.zip
 * Site URL: Every site win 100001+ URLs or the site already sent with a private message to @mgedmin for the #65 

Regards

  Mirco

**Comment by cjmayo** [comment]
`URLs checked` is actually reporting the size of the results cache, which is limited.

https://github.com/linkchecker/linkchecker/blob/a977e4d7129450ba9fda8389724c80c1bde66883/linkcheck/director/status.py#L56-L57

https://github.com/linkchecker/linkchecker/blob/a977e4d7129450ba9fda8389724c80c1bde66883/linkcheck/director/console.py#L44-L45

So, probably just needs a rename of the label.

**Comment by cjmayo** [comment]
Ah, OK  fc73c6ca6ea gives a clue to the intended meaning "Log number of checked unique URLs.".

**Comment by mkudlacek** [comment]
Hi, I am experiencing the same issue, but a bit more on the PITA side. Once the linkchecker hits the magic number, the memory consumption rises.

![image](https://user-images.githubusercontent.com/146914/100427722-28564400-3093-11eb-8b2e-30f4d12e5e7a.png)

**Comment by phaer** [comment]
I think having a default limit of 100000 seems reasonable, but it might be a good idea to allow users to configure said limits, I am trying to do that in #544.

@mkudlacek Maybe I am missing something, but increased memory usage upon a filled cache seems like expected behaviour, no?
