### ISSUE TITLE
How do I check for only 404 (not 403 errors)?  I use Windows

### ISSUE THREAD

**Issue by Hueg** [linkchecker/linkchecker#465]
How do I check for only 404 (not 403 errors)? I use Windows

**Comment by cjmayo** [comment]
This is not currently supported.

Perhaps excluding the links that cause a 403 might be a workaround, `--ignore-url`:
https://linkchecker.github.io/linkchecker/man1/linkchecker.1.html#Checking_options

or `ignore` in linkcheckerrrc:
https://linkchecker.github.io/linkchecker/man5/linkcheckerrc.5.html#_fB_filtering__fP

**Comment by Martiix** [comment]
Was wondering about the same thing... Getting a lot of 503 errors while websites are temporary down, which can be annoying.
