### ISSUE TITLE
How to see the result after LinkChecker is finished?

### ISSUE THREAD

**Issue by Hueg** [linkchecker/linkchecker#466]
My program just seems to shut down when it is finished checking - is there a way to keep it open - or to make it save the result in a file 

I run it to see 404 errors - but I can only see the result while the program is still checking links?

**Comment by cjmayo** [comment]
Results can be saved to a file in various formats with the `-F` option:
https://linkchecker.github.io/linkchecker/man1/linkchecker.1.html#Output_options

**Comment by Hueg** [comment]
hmm but if I write 
$ linkchecker http://example.com -f filename.txt 

It comes with the warning
```
C:\Program Files (x86)\LinkChecker> linkchecker http://example.com -f filename.txt 
 WARNING 2020-08-03 14:26:08,065 MainThread Unreadable config file: 'filename.txt'
```

so it seems as I should save an empty txt file somewhere? but I am not allowed to save an empty file in C:\Program Files (x86)\LinkChecker so where or how should I do this? :) 



same happens with --file-output
```
$  linkchecker http://example.com --file-output=text 

C:\Program Files (x86)\LinkChecker> linkchecker http://example.com --file-output=text
INFO 2020-08-03 14:19:01,976 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
WARNING 2020-08-03 14:19:01,984 MainThread Could not open file 'linkchecker-out.txt' for writing: [Errno 13] Permission denied: 'linkchecker-out.txt'
```

**Comment by cjmayo** [comment]
> hmm but if I write
> $ linkchecker http://example.com -f filename.txt

That should be capital `-F`

> 
> so it seems as I should save an empty txt file somewhere? but I am not allowed to save an empty file in C:\Program Files (x86)\LinkChecker so where or how should I do this? :)
> 

I don't know how the Windows version you have installed works. Perhaps change to a directory that you do have write access to and  run `C:\Program Files (x86)\LinkChecker\linkchecker` (plus your options).

Else as per the manual:
 `-FTYPE[/ENCODING][/FILENAME], --file-output=TYPE[/ENCODING][/FILENAME]`

something like: `--file-output=text/C:\temp\log.txt`

Again, haven't tried that on Windows.

**Comment by cjmayo** [comment]
> > hmm but if I write
> > $ linkchecker http://example.com -f filename.txt
> 
> That should be capital `-F`
> 
> > so it seems as I should save an empty txt file somewhere? but I am not allowed to save an empty file in C:\Program Files (x86)\LinkChecker so where or how should I do this? :)
> 

If you meant to create your own linkcheckerrc then try passing the full path to the file. (One may well have been created somewhere in C:\Users or wherever Windows stores user data).

**Comment by Hueg** [comment]
but I have to create an empty file first?

**Comment by Hueg** [comment]
uuu this works:

linkchecker http://example.com --file-output=text/C:\temp\log.txt

and then I should be able to find the file at C:\temp\log.txt correct ?

**Comment by Hueg** [comment]
thank you so much

**Comment by cjmayo** [comment]
Glad it's working!
