### ISSUE TITLE
automatically build binaries and tarballs

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#5]
right now, the main website is out of date: it points to the old 9.3 releases, which are stored as binaries in git.

that's bad.

releases should be automatically built from git tags in github and binaries should be built by travis and distributed from there.

**Comment by seamang** [comment]
What about building the windows binary? AFAIK that would need another procedure?

**Comment by anarcat** [comment]
don't travis have windows builders?

no idea.

**Comment by mgedmin** [comment]
Travis doesn't have Windows builders at the moment, but there's Appveyor CI which is like Travis, except for Windows.

Here's an example project that uses Appveyor to build Python wheels and upload them to PyPI for every git tag: https://github.com/zopefoundation/zope.interface/blob/master/appveyor.yml

**Comment by cjmayo** [comment]
No more binary executables, but sdist and wheel are created automatically on release now by https://github.com/linkchecker/linkchecker/blob/master/.github/workflows/release-files.yml.

PyPA have an Action that we could use to publish automatically to PyPI - but would mean creating a project token and storing in GitHub. Is it worth it?

Above workflow logs the sha256sums which can be compared (while the log persists) with those calculated by PyPI.
