### ISSUE TITLE
How to prevent syntax checking?

### ISSUE THREAD

**Issue by akashisama** [linkchecker/linkchecker#50]
Hi. Is it possible to prevent syntax checking on specific urls? I'd like to not have mailto links checked. When I use ```--ignore-url ^mailto:``` I still receive errors for incorrectly formatted emails (eg ```Error: Missing local part of mail address `@15m'.```. Cheers.

**Comment by yanetveliz** [comment]
Hi,  I have a situation with slack URLs as "slack://channel?team=".
I used `linkchecker --no-warning --ignore-url=".*slack.*" public/index.html` 
and the console shows 
`URL        `slack://channel?team=...'
Name       `#name'
Parent URL file:///test/public/index.html, line 20, col 37
Real URL   slack://channel?team=...
Info         **The URL is outside of the domain filter, checked only syntax.**
Result     **Error: URL is unrecognized or has invalid syntax**
`
How can I use the --ignore-url to prevent syntax checking as the doc explains.

**Comment by cjmayo** [comment]
> Hi. Is it possible to prevent syntax checking on specific urls? I'd like to not have mailto links checked. When I use `--ignore-url ^mailto:` I still receive errors for incorrectly formatted emails (eg `` Error: Missing local part of mail address `@15m'. ``. Cheers.

`--ignore-url` does not stop syntax checking. The `--help` does state this, but not the man page, I've proposed an update on #470.

However, the `allowedschemes` setting in linkcheckerrc can be used to exclude mailto from all checking e.g. `allowedschemes=file,http,https`.

**Comment by cjmayo** [comment]
> Hi, I have a situation with slack URLs as "slack://channel?team=".

This we can permanently fix, removing the need for any configuration. I think `slack://` is only for opening a local client and so there is nothing useful LinkChecker can do? I've included this in #475.
