### ISSUE TITLE
Can `linkchecker` be extendedd to Pandoc-flavoured markdown?

### ISSUE THREAD

**Issue by kleinbottle** [linkchecker/linkchecker#502]
## Summary

Let `testfile.md` contain the following line:

`linkchecker` does not seem to work with Pandoc-flavoured Markdown links:

`<https://madeupname.com>` and `[My Website](https://madeupname.com)`

## Steps to reproduce

`linkchecker --check-extern testfile.md`

## Actual result

`That's it. 1 link in 1 URL checked. 0 warnings found. 0 errors found.`

## Expected result

St least one error depending on URL syntax that is recognized.

## Environment

lsb_release -a:
 * Operating system:  lsb_release -a: 
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.1
Codename:       Mikah
 * Linkchecker version: 
 * Python version: LinkChecker 10.0.0.dev0 released xx.xx.xxxx
Copyright (C) 2000-2014 Bastian Kleineidam
 * Install method: Arch User Repo (AUR) for `linkchecker-git`
 * Site URL: 

## Logs

LinkChecker 10.0.0.dev0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues

Start checking at 2020-09-14 19:33:37+005

Statistics:
Downloaded: 0B.
Content types: 0 image, 0 text, 0 video, 0 audio, 1 application, 0 mail and 0 other.
URL lengths: min=23, max=23, avg=23.

That's it. 1 link in 1 URL checked. 0 warnings found. 0 errors found.
Stopped checking at 2020-09-14 19:33:39+005 (2 seconds)

## Other notes

Featrure request

**Comment by cjmayo** [comment]
There is a MarkdownCheck plugin, but it isn't documented in the man page... (I've created #503 for that).

At the end of `linkcheckerrc`, do uncomment `#[MarkdownCheck]` and give that a try.

**Comment by kleinbottle** [comment]
> There is a MarkdownCheck plugin, but it isn't documented in the man page... (I've created #503 for that).
> 
> At the end of `linkcheckerrc`, do uncomment `#[MarkdownCheck]` and give that a try.

I have uncommented just that one line on  `/usr/share/linkchecker/linkcheckerrc` and run the command 

`linkchecker --check-extern test.md`

where `test.md` is

```
This is for [Amazon.com](https://amazon.com).

<https://amazon.com>

This too is  for [Amazon.com][amazon].

[amazon]: https://amazon.com

This is the non-existent [SwanLotus site](https://swanlotus.org/).

<https://swanlotus.org/>

This too is the non-existent [SwanLotus site][swanlotus].

[swanlotus]: https://swanlotus.org

```

The log does not indicate any errors:

> LinkChecker 10.0.0.dev0              Copyright (C) 2000-2014 Bastian Kleineidam
> LinkChecker comes with ABSOLUTELY NO WARRANTY!
> This is free software, and you are welcome to redistribute it
> under certain conditions. Look at the file `LICENSE' within this
> distribution.
> Get the newest version at https://linkchecker.github.io/linkchecker/
> Write comments and bugs to https://github.com/linkchecker/linkchecker/issues
> 
> Start checking at 2020-09-16 00:15:20+005
> 
> Statistics:
> Downloaded: 0B.
> Content types: 0 image, 0 text, 0 video, 0 audio, 1 application, 0 mail and 0 other.
> URL lengths: min=19, max=19, avg=19.
> 
> That's it. 1 link in 1 URL checked. 0 warnings found. 0 errors found.
> Stopped checking at 2020-09-16 00:15:21+005 (1 seconds)

I am afraid that it does not seem to work. Please let me know if I have made an error.

**Comment by kleinbottle** [comment]
Oops. I think I have inadvertently closed this issue. Please open it. My itention was simply to add  feedback on what happened.

**Comment by cjmayo** [comment]
`/usr/share/linkchecker/linkcheckerrc` is the template that is used to create the user configuration file. Do check `~/.linkchecker/linkcheckerrc` or `${XDG_CONFIG_HOME}/linkchecker/linkcheckerrc`.

**Comment by kleinbottle** [comment]
> `/usr/share/linkchecker/linkcheckerrc` is the template that is used to create the user configuration file. Do check `~/.linkchecker/linkcheckerrc` or `${XDG_CONFIG_HOME}/linkchecker/linkcheckerrc`.

On my system, this appears to be `~/.config/linkchecker/linkcheckerrc`

I have uncommented the relevant line.

Running it on `test.md` gives two errors as expected. The red lines are:

> Error: ConnectionError: HTTPSConnectionPool(host='swanlotus.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45284a7280>: Failed to establish a new connection: [Errn...

It works now.

Thanks.
