### ISSUE TITLE
--no-follow-url appears to be ignored

### ISSUE THREAD

**Issue by dwreski** [linkchecker/linkchecker#508]
## Steps to reproduce

I've tried numerous variations using a number of different regexes to exclude social media sharing and all appear to be ignored. What am I doing wrong?

linkchecker https://linuxsecurity.com --verbose --check-extern --no-follow-url=https://linkedin.com/.* --no-follow-url=https://accounts.google.com/.* --no-follow-url=https://facebook.com/.* --no-follow-url=https://www.twitter.com/.* --no-follow-url=https://plus.google.com/.* --no-follow-url=https://www.facebook.com/.* --no-follow-url=https://twitter.com/.* --no-follow-url=https://www.linkedin.com/.* --file-output=csv/linuxsecurity-linkchecker-092320a.csv

## Actual result
`URL        `https://plus.google.com/share?url=https://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-
kernel-updates-on-linux'
Name       `Share On Google Plus'
Parent URL https://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux, line 459, 
col 1
Base       https://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux
Real URL   https://accounts.google.com/ServiceLogin?passive=1209600&osid=1&continue=https://plus.google.com/up/?continue%3Dhttps://plus.google.com/share?url%253Dhttps://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux&followup=https://plus.google.com/up/?continue%3Dhttps://plus.google.com/share?url%253Dhttps://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux
Check time 1.494 seconds
Info       Redirected to
           `https://plus.google.com/up/?continue=https://plus.google.com/share?url%3Dhttps://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux'.
           Redirected to
           `https://accounts.google.com/ServiceLogin?passive=1209600&osid=1&continue=https://plus.google.com/up/?continue%3Dhttps://plus.google.com/share?url%253Dhttps://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux&followup=https://plus.google.com/up/?continue%3Dhttps://plus.google.com/share?url%253Dhttps://linuxsecurity.com/howtos/learn-tips-and-tricks/how-to-setup-automatic-kernel-updates-on-linux'.
`
## Environment

 * Operating system: fedora32
 * Linkchecker version: inkChecker 10.0.0.dev1
 * Python version: Python 3.8.5
 * Install method: built from SRPM
 * Site URL: https://linuxsecurity.com

## Configuration file

default included with source

**Comment by cjmayo** [comment]
`--no-follow-url` will look up the URL, just not parse the page:
https://linkchecker.github.io/linkchecker/man/linkchecker.html#cmdoption-no-follow-url

Perhaps `--ignore-url` would be a better fit, only syntax checks the URL:
https://linkchecker.github.io/linkchecker/man/linkchecker.html#cmdoption-ignore-url
