### ISSUE TITLE
Is there a way to disable certificate checking?

### ISSUE THREAD

**Issue by DylanDonkersgoed** [linkchecker/linkchecker#511]
I'm using this program to check links on a local site. Mostly it works pretty well but it's having trouble retrieving HTTPS links. While the site is accessible via http as well locally some of the links in the content point directly to https URLs and can't easily be updated. The script is failing for the HTTPS links with this error:

```
Error: SSLError: HTTPSConnectionPool(host='<omitted>.dev.localhost', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issu...
```

that's not really surprising since my .dev.localhost domain of course does not have a proper externally signed certificate. Though some other programs (e.g. curl) do seem to be able to verify the cert.

Is there any way I can disable certificate checking for linkchecker? Perhaps some generic Python method that will work with it? I'm fairly confident no-one is running a MITM attack on my desktop.

**Comment by cjmayo** [comment]
Yes, do try `sslverify`:
https://linkchecker.github.io/linkchecker/man/linkcheckerrc.html
