### ISSUE TITLE
Suggestion - listing active threads in HTML output

### ISSUE THREAD

**Issue by gvmelle** [linkchecker/linkchecker#526]
If output file is html it would be nice tot put the lines with '10 threads active ...... seconds' in a unorderd list like:
&lt;ul&gt;        
&lt;li&gt;10 threads active,   445 links queued,  617 links in 1075 URLs checked, runtime 3 minutes, 6 seconds&lt;/li&gt;
&lt;li&gt;10 threads active,   431 links queued,  631 links in 1075 URLs checked, runtime 3 minutes, 11 seconds&lt;/li&gt;
&lt;/ul&gt;
or, if not possible to end the line with a &lt;br&gt;

**Comment by cjmayo** [comment]
But, surely the threads active is not included in the html output. Is this redirecting stderr and stdout to a file?

Suggest using `-F html/<filename>`.

If I misunderstood please reopen.
