### ISSUE TITLE
warnings from debian about wsgi wrapper

### ISSUE THREAD

**Issue by anarcat** [linkchecker/linkchecker#529]
I get this while building the Debian package:

```
E: linkchecker-web: script-uses-unversioned-python-in-shebang usr/lib/cgi-bin/lc.wsgi
W: linkchecker-web: unusual-interpreter usr/lib/cgi-bin/lc.wsgi #!/usr/bin/python
```

The latter should probably be `/usr/bin/python3`, fir off... or better, managed by the installer somehow. The other error, i'm not sure about... I'll still ship 10.0.0 as is in Debian, but just a heads up...

**Comment by anarcat** [comment]
> That was fortunate - the WSGI wrapper was broken by 4f3f1ac.

not sure i follow... what was fortunate?

**Comment by cjmayo** [comment]
I just meant in that there was an error in the Debian packaging and you reported it. Otherwise the other bug had gone unnoticed and the test suite didn't pick it up.

**Comment by cjmayo** [comment]
10.0.1 released with the fix.
