### ISSUE TITLE
How can we run linkchecker with proxy details ?

### ISSUE THREAD

**Issue by vyshnavarajesh** [linkchecker/linkchecker#532]
How can we run linkchecker with proxy details ?
My website runs behind a proxy, does link checker support proxy ?

**Comment by cjmayo** [comment]
Proxy support is describe here:
https://linkchecker.github.io/linkchecker/man/linkchecker.html#proxy-support

There are open issues with proxy support.

Please only ask a question once and never add new questions to existing tickets.
