### ISSUE TITLE
docker image of linkchecker is huge, should we optimize it?

### ISSUE THREAD

**Issue by oupala** [linkchecker/linkchecker#538]
## Summary

docker image of linkchecker is huge, should we optimize it?

## Steps to reproduce

 1. pull linkchecker docker image
 2. see that the image is 899 MB
 3. optimise the image using `docker-slim build linkchecker/linkchecker`
 4. see that the optimized image is 34.8 MB

## Actual result

A huge docker image binary.

## Expected result

A smaller docker image binary.

## Environment

 * Operating system: linux 
 * Linkchecker version: 9.4 
 * Python version: N/A 
 * Install method: docker image 
 * Site URL: 

## Configuration file

N/A

## Logs

```log
cmd=build info=results status='MINIFIED' by='25.85X' size.original='898 MB' size.optimized='35 MB' 
cmd=build info=results image.size='35 MB' has.data='true' image.name='linkchecker/linkchecker.slim'
```

## Other notes

The minified image does not work out of the box as there is missing certificate store, But I still think that there is room for improvement.

The [current Dockerfile](https://github.com/linkchecker/linkchecker/blob/365852a4428bf9fe7e58fa0f7f2845719d531182/Dockerfile) is pretty simple and base on a slim distro (`python:3-slim`).

A dive into the image (using `wagoodman/dive` image) shows that this base image is not that small: 115 MB. But the biggest issue is that when I build my own image based on the official Dockerfile, I get an image that is 129 MB big. And when I dive into the official image, I can see steps that are not in the offficial Dockerfile. Hence the official image has not been built from the official Dockerfile.

Is there anyway to explain such thing?

**Comment by matkoniecz** [comment]
Is docker image really necessary? Maybe solution for this and #537 would be to remove it from README completely?

Note that there is already

> The Docker images are out-of-date, pip installation is the only currently recommended method.

in  the readme

**Comment by oupala** [comment]
Docker image is really useful in a CI environment (Continuous Integration). For example, GitLab CI pipeline rely on containers, and hence on Docker images.

Maybe @ruzickap @Barabazs @alberto56 and @cjmayo have an opinion about that issue.

**Comment by alberto56** [comment]
I maintain a version of linkchecker on a Docker image; I have a Jenkins job which automatically updates it weekly so it's always up to date.

It is at https://hub.docker.com/r/dcycle/broken-link-checker/tags?page=1&ordering=last_updated

You'll notice that it is a lot smaller than the official image, and it also reinstalls the latest version of linkchecker weekly:

```
$ docker run --rm dcycle/broken-link-checker:2 --version
WARNING linkcheck.check 2021-09-08 19:51:27,201 MainThread Running as root user; dropping privileges by changing user to nobody.
LinkChecker 10.0.1 released 29.1.2021
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors

```

The code is at https://github.com/dcycle/docker-broken-link-checker.

It's also not that huge, 336.97 MB

Perhaps you'd like to link to my Docker project instead of maintaining your own.

**Comment by cjmayo** [comment]
Image created by #576 is 136MB according to `docker images`. With 122MB being python:3.9-slim.

`docker-slim` does look clever at first look. I think I need a bit more time to understand! Not sure yet if we would get enough benefit for adding complexity (how to the workflow?) and a dependency. Plus from the above numbers updating our bit would only be 14MB anyway.

**Comment by oupala** [comment]
Image has already lost some weight starting from 899 Mo to 136 Mo today.

The suggested use of `docker-slim` was just there to see how much room there was for improvement and optimizations. I don't think that `docker-slim` should be integrated to the workflow.

**Comment by cjmayo** [comment]
And at the moment it is only a 4MB update for subsequent pulls.

OK, thanks I'll close this one now.
