### ISSUE TITLE
Test failures on master

### ISSUE THREAD

**Issue by mgedmin** [linkchecker/linkchecker#547]
Periodic GitHub actions build started failing recently.  Example: https://github.com/linkchecker/linkchecker/runs/3149190300?check_suite_focus=true

It looks like BeautifulSoup changed fallback charset to UTF-8 instead of ASCII, which makes two of our tests fail.

(We probably need to adjust test expectations, after some checking if that's okay.)

**Comment by cjmayo** [comment]
Requests 2.26.0 is now pulling in charset_normalizer instead of chardet.
https://docs.python-requests.org/en/latest/community/updates/#id1

Might be that, haven't tested. If so looks like one option is to install chardet first.
