### ISSUE TITLE
Add way to silence "Checking intern URLs only; use --check-extern to check extern URLs.","

### ISSUE THREAD

**Issue by matkoniecz** [linkchecker/linkchecker#552]
## Summary

I want to run linkchecker to generate csv file and parse it looking for issues including borken links and orphaned pages.

But I get this message in stderr and it is pointless to me - I can redirect entire stderr to `/dev/null` but it would more likely that I will miss or make harder to debug actual errors.

I see value in showing it by default but I want option to get rid of it.

https://github.com/linkchecker/linkchecker/blob/365852a4428bf9fe7e58fa0f7f2845719d531182/linkchecker#L574

## Steps to reproduce

 1. have index.html file
 2. `linkchecker index.html --verbose -o csv > test.csv`

## Actual result
`INFO linkcheck.cmdline 2021-08-13 10:19:54,332 MainThread Checking intern URLs only; use --check-extern to check extern URLs.`

## Expected result
Empty stderr or option to achieve this.

## Environment

 * Operating system:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

 * Linkchecker version:

```
LinkChecker 10.0.1 released 29.1.2021
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors
```

 * Python version: 

```
Python 3.8.10
```

 * Install method: from git as requested in readme
 * Site URL: local file

## Configuration file

None

`cat: /home/mateusz/.linkchecker/linkcheckerrc: No such file or directory`

## Other notes

https://github.com/linkchecker/linkchecker/blob/365852a4428bf9fe7e58fa0f7f2845719d531182/linkchecker#L574

**Comment by cjmayo** [comment]
Change to make `quiet/-q` silence all INFO messages in #569.

**Comment by cjmayo** [comment]
`linkchecker index.html --verbose -o csv > test.csv`

could then be:

`linkchecker index.html -q -v -F csv/test.csv`

**Comment by cjmayo** [comment]
Now silenced by `-q`.
