### ISSUE TITLE
CSV (COMMA separated values) is separating them using semicolon

### ISSUE THREAD

**Issue by matkoniecz** [linkchecker/linkchecker#553]
## Summary

I would expect commas to be used in CSV or at least warn that semicolons are used

Docs in `linkchecker --help` 

> csv     Log check result in CSV format with one URL per line.

## Steps to reproduce

 1. `linkchecker index.html --verbose -o csv > linkchecker_data.csv 2>/dev/null` (can be run in a folder without prepared files)
 2.  `cat linkchecker_data.csv`

## Actual result

semicolon separation between fields

## Expected result

comma separation

## Environment

 * Operating system:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

 * Linkchecker version:

```
LinkChecker 10.0.1 released 29.1.2021
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors
```

 * Python version: 

```
Python 3.8.10
```

 * Install method: from git as requested in readme
 * Site URL: local file

## Configuration file

None

`cat: /home/mateusz/.linkchecker/linkcheckerrc: No such file or directory`
## Logs

```
linkchecker index.html --verbose -o csv
INFO linkcheck.cmdline 2021-08-14 14:07:10,471 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
# created by LinkChecker at 2021-08-14 14:07:10+002
# Get the newest version at https://linkchecker.github.io/linkchecker/
# Write comments and bugs to https://github.com/linkchecker/linkchecker/issues
urlname;parentname;base;result;warningstring;infostring;valid;url;line;column;name;dltime;size;checktime;cached;level;modified
file:///home/mateusz/index.html;;;URLError: <urlopen error [Errno 2] No such file or directory: '/home/mateusz/index.html'>;;;False;file:///home/mateusz/index.html;index.html;-1;-1;0.0011594295501708984;0;0;
# Stopped checking at 2021-08-14 14:07:11+002 (1 seconds)
```

**Comment by matkoniecz** [comment]
If docs change should happen: not sure what of https://github.com/linkchecker/linkchecker/search?q=CSV+format+with+one listed pages should be modified and what simply regenerated

https://github.com/linkchecker/linkchecker/blob/365852a4428bf9fe7e58fa0f7f2845719d531182/linkcheck/logger/csvlog.py#L56 is a place where separator may be modified - but it would be backward incompatible

**Comment by cjmayo** [comment]
The separator changed to a semicolon in 2010 851e1121e. Documentation update in #569.

The CSV name is widely used like this see e.g. the Python csv module documentation.

**Comment by cjmayo** [comment]
Documentation published:
https://linkchecker.github.io/linkchecker/man/linkcheckerrc.html#csv
