### ISSUE TITLE
 Option to ignore tag: <meta name="robots" content="nofollow"> #806 

### ISSUE THREAD

**Issue by octavsly** [linkchecker/linkchecker#557]
If the HTML contains `<meta name="robots" content="nofollow">` only one file i checked.
I would like to keep this in my HTML but still check all the links.
`--no-robots` option is not working for this construct. Another option? or reuse the `--no-robots`?

**Comment by guaka** [comment]
duplicate with #374

**Comment by cjmayo** [comment]
Closing as duplicate. Thanks @guaka.
