### ISSUE TITLE
 Use of __file__ prevents packaging with PyOxidizer

### ISSUE THREAD

**Issue by agxies** [linkchecker/linkchecker#560]
I tried to build a single Windows executable of linkchecker by using [pyoxidizer](https://github.com/indygreg/PyOxidizer). 
As mentioned here: indygreg/PyOxidizer#69, this fails because linkchecker uses `__file__` to derive the filesystem path, which is an optional python feature. 
Maybe it would be possible to remove the dependency of `__file__` from linkchecker.
I don't know if this could actually work, but a single executable would be really nice for integration in existing workflows and should also bring some performance benefits.

**Comment by matkoniecz** [comment]
> As mentioned here: indygreg/PyOxidizer#69, this fails because linkchecker uses __file__ to derive the filesystem path

it contains

> Instructions for writing portable Python code that doesn't rely on __file__ can be found at https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#reliance-on-file.

and https://pyoxidizer.readthedocs.io/en/latest/packaging_pitfalls.html#reliance-on-file is a 404 page

**Comment by cjmayo** [comment]
#560 includes changes and a pyoxidizer.bzl that creates a binary for me that seems to work (not extensively tested).
