### ISSUE TITLE
Trouble with windows instalation.

### ISSUE THREAD

**Issue by fassina2** [linkchecker/linkchecker#562]
Here's what I try doing in powershell and the error I get: 
PS C:\Users\Fassina> pip3 install git+https://github.com/linkchecker/linkchecker.git
Collecting git+https://github.com/linkchecker/linkchecker.git
  Cloning https://github.com/linkchecker/linkchecker.git to c:\users\fassina\appdata\local\temp\pip-req-build-ic_l91hm
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

Help I don't know what I'm doing wrong. I remember using 9.3 and it was just a normal install, but that version doesn't seem to work anymore.

**Comment by cjmayo** [comment]
The missing command, git can be downloaded from:
https://git-scm.com/downloads

But at the moment LinkChecker 10.0.1 available from PyPI is not that behind, so `pip3 install linkchecker` would be easier.
