### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'multi_valued_attributes'

### ISSUE THREAD

**Issue by NoCanDouCan** [linkchecker/linkchecker#566]
## Summary

Not sure if there is a general problem but I installed the program and it displays always the same error for all websites tested.
Tested it again on a Ubuntu 20 LTS machine and it worked.

## Steps to reproduce

 1. pip3 install git+https://github.com/linkchecker/linkchecker.git
 2. linkchecker https://github.com

## Actual result
Error:
TypeError: __init__() got an unexpected keyword argument 'multi_valued_attributes'

## Expected result
No error

## Environment

 * Operating system: Ubuntu 16.04.6 LTS
 * Linkchecker version: 10.0.1
 * Python version: Python 3.7.10 (default, Feb 20 2021, 21:21:24)
 * Install method: pip3 install git+https://github.com/linkchecker/linkchecker.git
 * Site URL: any, tested with multiple websites, used this as example: https://github.com

## Logs

WARNING linkcheck.check 2021-11-22 16:24:38,192 MainThread Running as root user; dropping privileges by changing user to nobody.
INFO linkcheck.cmdline 2021-11-22 16:24:38,193 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 10.0.1
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it under
certain conditions. Look at the file `LICENSE' within this distribution.
Get the newest version at https://linkchecker.github.io/linkchecker/
Write comments and bugs to https://github.com/linkchecker/linkchecker/issues

Start checking at 2021-11-22 16:24:38+002

********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/linkchecker/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/director/checker.py", line 103, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://github.com, started 140065066440448)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://github.com, started 140065066440448)>>
      url_data = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/director/checker.py", line 115, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7f6371becb90>
      url_data = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self = <local> <Checker(CheckThread-https://github.com, started 140065066440448)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7f6371bc7450>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/director/checker.py", line 52, in check_url
    line: do_parse = url_data.check_content()
    locals:
      do_parse = <not found>
      url_data = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      url_data.check_content = <local> <bound method UrlBase.check_content of <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/checker/urlbase.py", line 549, in check_content
    line: if self.allows_recursion():
    locals:
      self = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self.allows_recursion = <local> <bound method UrlBase.allows_recursion of <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/checker/urlbase.py", line 647, in allows_recursion
    line: if not self.content_allows_robots():
    locals:
      self = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self.content_allows_robots = <local> <bound method HttpUrl.content_allows_robots of <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/checker/httpurl.py", line 98, in content_allows_robots
    line: soup = self.get_soup()
    locals:
      soup = <not found>
      self = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self.get_soup = <local> <bound method UrlBase.get_soup of <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/checker/urlbase.py", line 710, in get_soup
    line: self.get_content()
    locals:
      self = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self.get_content = <local> <bound method HttpUrl.get_content of <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>>
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/checker/httpurl.py", line 318, in get_content
    line: return super().get_content(self.encoding)
    locals:
      super = <builtin> <class 'super'>
      get_content = <not found>
      self = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self.encoding = <local> 'utf-8'
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/checker/urlbase.py", line 721, in get_content
    line: self.soup = htmlsoup.make_soup(self.data, encoding)
    locals:
      self = <local> <https link, base_url='https://github.com', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=None, column=None, page=0, name='', anchor='', cache_url=https://github.com>
      self.soup = <local> None
      htmlsoup = <global> <module 'linkcheck.htmlutil.htmlsoup' from '/usr/local/lib/python3.7/dist-packages/linkcheck/htmlutil/htmlsoup.py'>
      htmlsoup.make_soup = <global> <function make_soup at 0x7f63733575f0>
      self.data = <local> b'\n\n\n\n\n\n<!DOCTYPE html>\n<html lang="en" >\n  <head>\n    <meta charset="utf-8">\n  <link rel="dns-prefetch" href="https://github.githubassets.com">\n  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws...., len = 277583
      encoding = <local> 'utf-8'
  File "/usr/local/lib/python3.7/dist-packages/linkcheck/htmlutil/htmlsoup.py", line 34, in make_soup
    line: markup, "html.parser", from_encoding=from_encoding, multi_valued_attributes=None
    locals:
      markup = <local> b'\n\n\n\n\n\n<!DOCTYPE html>\n<html lang="en" >\n  <head>\n    <meta charset="utf-8">\n  <link rel="dns-prefetch" href="https://github.githubassets.com">\n  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws...., len = 277583
      from_encoding = <local> 'utf-8'
      multi_valued_attributes = <not found>
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 143, in __init__
    line: "__init__() got an unexpected keyword argument '%s'" % arg)
    locals:
      arg = <local> 'multi_valued_attributes', len = 23
TypeError: __init__() got an unexpected keyword argument 'multi_valued_attributes'
System info:
LinkChecker 10.0.1
Released on: 29.1.2021
Python 3.7.10 (default, Feb 20 2021, 21:21:24)
[GCC 5.4.0 20160609] on linux
Modules: Beautiful Soup, dnspython, Requests, PyXDG, Pysqlite, Sqlite
Local time: 2021-11-22 16:24:38+002
sys.argv: ['/usr/local/bin/linkchecker', 'https://github.com', '--verbose']
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2021-11-22 16:24:38,285 CheckThread-https://github.com internal error occurred

Statistics:
Downloaded: 271.08KB.
No statistics available since no URLs were checked.

That's it. 0 links in 1 URL checked. 0 warnings found. 0 errors found.
There was 1 internal error.
Stopped checking at 2021-11-22 16:24:39+002 (1 seconds)

## Other notes

I guess that it is a environment issue of my system.

**Comment by cjmayo** [comment]
This: "/usr/lib/python3/dist-packages/bs4/init.py" looks like the problem. It is using Ubuntu's copy of Beautiful Soup which must be very old on 16.04. And would explain why it works 20 LTS machine.

Getting `pip` to install a newer version of `beautifulsoup4` should do the trick.

Thanks for the report. We put the minimum version of Beautiful Soup in the documentation but not in setup.py. Linked PR fixes that.
