### ISSUE TITLE
Cannot execute linkchecker on Windows

### ISSUE THREAD

**Issue by felix-hilden** [linkchecker/linkchecker#577]
## Summary
I cannot execute linkchecker after installation.

## Steps to reproduce
 1. Setup environment on Windows using pip and virtualenv
 2. Install `linkchecker` using `pip install linkchecker` (later also `pip install git+https://github.com/linkchecker/linkchecker.git`)
 3. Run `linkchecker --help` (also with `linkcheck`, `LinkChecker` and `LinkCheck`, `python -m linkcheck` etc.)

## Actual result
Command was not found (or the module cannot be executed with `python -m`).

## Expected result
At least some output.

## Environment
Windows 10, Python 3.9, pip, virtualenv, then pip install again.

 * Operating system: Windows 10
 * Linkchecker version: 10.0.1 and the current main
 * Python version: 3.9.4
 * Install method: pip/pypi and pip/git

## Other notes
I tried to look for the command line entry point in the source, but didn't find it. Also, the choice to use `LinkChecker` as the package name but `linkcheck` as the module name is a bit odd, but anyways. I can `pip show` the package just fine.

Am I missing something obvious? 😅

**Comment by cjmayo** [comment]
LinkChecker is over 20 years old,  you didn't miss an entry point.
I have installed on Windows once, from memory the executable is there - keep looking! - just not in the PATH variable.
N.B. as pointed out in https://linkchecker.github.io/linkchecker/install.html#setup-for-windows even MS recommends WSL for web development!

**Comment by felix-hilden** [comment]
I see, it seems to be a python script without an extension in my virtual environment's "Scripts" folder. It is in my PATH, but Windows doesn't execute Python scripts on the command line using a bang.

Would you consider modernising the approach a little, by using setuptools entry points for the command line scripts or even just `python -m linkchecker`? They would be cross-platform by design. Recommending WSL is not really "supporting Windows". It's just Windows supporting Linux. And while I respect the fact that this library is old, it isn't really an excuse for things working suboptimally either 😅 especially because you already require Python 3.6.

I'd be happy to check out how they can be implemented for linkchecker if you can guide me to the place where the script is generated.

**Comment by cjmayo** [comment]
> I see, it seems to be a python script without an extension in my virtual environment's "Scripts" folder. It is in my PATH, but Windows doesn't execute Python scripts on the command line using a bang.

Thanks for reporting back. I think I'm remembering creating a batch file now.

Quoting from install.txt:

> Setup for Windows
> -----------------
> Python from the Microsoft Store does include pip_, but installing
within Windows Subsystem for Linux (WSL) is the preferred option:
https://docs.microsoft.com/en-us/windows/python/beginners

Perhaps a little understated but then we are not trying to tell people what to do. WSL is the current situation.

Before moving from that position it would need to be shown that LinkChecker actually works on Windows.
i.e. getting the test suite working #494.

I did have a look at creating an entry point, and stopped - it is not a small job.

**Comment by felix-hilden** [comment]
Fair enough, thanks for responding! If you'd like to keep this open, I'm all up for it. But if you think supporting Windows is too big at the moment, feel free to close this issue 👍

**Comment by cjmayo** [comment]
I think it is useful to keep it open - I wouldn't be surprised if there are other people with the same question - but yes, with the "help wanted" status.

**Comment by cjmayo** [comment]
Entry point created by PR #600.
