### ISSUE TITLE
Mailto links not picked up in the scan

### ISSUE THREAD

**Issue by theqaguy1** [linkchecker/linkchecker#588]
## Summary
Mailto links not picked up in the scan. Maybe a setting? 
https://linkchecker.github.io/linkchecker/man/linkchecker.html#performed-checks
_Mail links (mailto:)
A mailto: link eventually resolves to a list of email addresses. If one address fails, the whole list will fail. For each mail address we check the following things:

Check the address syntax, both the parts before and after the @ sign.

Look up the MX DNS records. If we found no MX record, print an error.

Check if one of the mail hosts accept an SMTP connection. Check hosts with higher priority first. If no host accepts SMTP, we print a warning.

Try to verify the address with the VRFY command. If we got an answer, print the verified address as an info._

## Steps to reproduce

 1. run: python linkchecker https://www.example.com --file-output=csv --verbose
 2. check the output file for "mailto"
3. example of a link on the site: <a target="_blank" href="mailto:email@example.com" class="">email@example.com</a>

## Actual result
No mailto links are output

## Expected result
mailto links are output.

## Environment

 * Operating system: Windows 10
 * Linkchecker version: 10.0.1
 * Python version: 3.8
 * Install method: pip install linkchecker
 * Site URL: don't want to add but i can see it is able to get mailto links from other site.

## Configuration file
no changes to configuration file since install.

## Logs

 python linkchecker https://www.example.com --file-output=csv --verbose

## Other notes
Working on other sites I have tried and mailto is exported.

**Comment by cjmayo** [comment]
There are only a few data points here, one being this is running on Windows. We don't have a running test suite on Windows, #494. It is unclear the extent to which LinkChecker 10 works on Windows. The advice in install.txt is to use WSL https://linkchecker.github.io/linkchecker/install.html#setup-for-windows.

Regardless of the OS, running with debug `-D checking` would hopefully give some pointers to the problem.

**Comment by theqaguy1** [comment]
Hi, I ran debug and piped out to a file. 
`python -u linkchecker -Dall --file-output=csv -v https://www.example.com 2>&1 | tee test.txt `

After much of my own debugging I can see that emails have protection in the HTML and why they are not picked up.

```
<html>
<body>
<!--StartFragment-->

<div class="card-body">
--
  | You should contact us at <a target="_blank" href="/cdn-cgi/l/email-protection#0f6c7f6c4f7d7c6e21666a"><span class="__cf_email__" data-cfemail="52312231122021337c3b37">[email&#160;protected]</span></a>
  | </div>

<!--EndFragment-->
</body>
</html>
```

I can see output in verbose mode:
```
URL        `/cdn-cgi/l/email-protection#d8bba8bb98aaabb9f6b1bd'
Name       `[emailáprotected]'
Parent URL https://example.com/examplepage, line 921, col 50
DEBUG linkcheck.check 2021-12-13 07:08:03,661 CheckThread-https://example.com/examplepage LinkFinder tag span attrs {}

```
will close as not linkchecker issue.
