### ISSUE TITLE
Not Escaping Ampersand in SVG / PS / Etc 

### ISSUE THREAD

**Issue by jvanalst** [linkchecker/linkchecker#609]
## Summary

-o dot option doesn't seem to escape ampersands in URLs leading to errors in SVG / PS / PDF (and possibly other prickly formats) when running them through a dot render.

## Steps to reproduce

Almost directly out of the documentation:
 1. linkchecker -o dot -v https://sites.google.com/a/ualberta.ca/luis-d-elia/ | dot -Tsvg -o outfile.svg
 2. linkchecker -o dot -v https://sites.google.com/a/ualberta.ca/luis-d-elia/ | dot -Tps -o outfile.ps
 3. linkchecker -o dot -v https://sites.google.com/a/ualberta.ca/luis-d-elia/ | dot -Tpdf -o outfile.pdf

## Actual result
- outfile.ps In the PS format the graph cuts off after the first element that contains an ampersand.
- outfile.svg SVG throws and error on line 42 at column 160: EntityRef: expecting ';'
- PDF renders a single mostly blank page with a single link on it that also seems to end after the ampersand

## Expected result
- usable documents in all cases (as in the case of a png where the full structure is rendered)

./linkchecker -o dot -v https://sites.google.com/a/ualberta.ca/luis-d-elia/ > outfile.dot
... find and replace "&" with "&amp;", and rename to infile.dot ...
dot -Tsvg infile.dot -o infile.svg
... SVG looks fine now ...
 dot -Tpdf infile.dot -o infile.pdf
 ... aside from an dimension error, PDF renders correctly.
 
## Environment
 * Operating system: Ubuntu 20.04 Focal
 * Linkchecker version: 10.1.0
 * Python version: 3.8.10
 * Install method: pip

## Configuration file
nil

## Logs
nil

## Other notes
- Should it all the URLs be run through an HTML/XML sanitizer/escaper regardless of format?
- Are there other formats with links where it matters one way or the other (it shouldn't really for gif, jpg, png, but it might for json which were all available out of the box with dot)?
- Should it be a separate command line argument --escape-links-for-xml or some such?

**Comment by cjmayo** [comment]
In the simple experiments I did ampersands were being percent encoded in the dot files.

For anyone that wants to look into this:

The loggers are reasonably self-contained:
https://github.com/linkchecker/linkchecker/blob/master/linkcheck/logger/dot.py

First step is probably to create a test that fails, not sure we have a good example though for loggers :
https://github.com/linkchecker/linkchecker/tree/master/tests/logger

**Comment by cjmayo** [comment]
Looking again, ampersands in queries are not encoded. But...

This is accepted as a [Graphviz issue](https://gitlab.com/graphviz/graphviz/-/issues/1687), and was fixed in [2.42.4 - 2020-04-05](https://gitlab.com/graphviz/graphviz/-/blob/main/CHANGELOG.md#2424-2020-04-05).

The bad news for Debian/Ubuntu users is the distribution version has not been updated for ages.

I can reproduce the problem with SVG on Ubuntu 20.04, not PS or PDF - but the above linked issue shows this is not a LinkChecker issue anyway.
