### ISSUE TITLE
Question: Basic Auth, linkchecker keeps asking for password

### ISSUE THREAD

**Issue by mkjaxxo** [linkchecker/linkchecker#610]
## Summary

I want to check an website behind a basic auth. This check should be automated but linkchecker keeps asking for a password.

## Steps to reproduce

 1. I added entry=.* <user> <password>  to linkcheckerrc config file
 2. I call linkchecker https://<url> -u <user> -p

## Actual result

I get 

`Enter LinkChecker password for user 3dvsreview at .+:`

## Expected result
Linkchecker should read the password from linkcheckerrc and start the check without user input.

## Environment

 * Operating system: Windows 10
 * Linkchecker version: LinkChecker 10.1.0
 * Python version: Python 3.9
 * Install method: PyPI

What am I doing wrong? Thanks.

**Comment by cjmayo** [comment]
I haven't used it but suggest trying without `-u -p`. 

That's what I understand the man page to be saying:

>  If the regular expression matches the checked URL, the given username/password pair is used for authentication. The command line options -u and -p match every link and therefore override the entries given here. 

https://linkchecker.github.io/linkchecker/man/linkcheckerrc.html#authentication

**Comment by mkjaxxo** [comment]
Thanks for your feedback. That saved me.

**Comment by alfador1** [comment]
Hey guys, can you explain a bit here. I don't understand that documentation. Any example?
