### ISSUE TITLE
Docker builds are outdated

### ISSUE THREAD

**Issue by wschoot** [linkchecker/linkchecker#625]
Right now, the `:latest` tag on https://hub.docker.com/r/linkchecker/linkchecker refers to a three year old build which runs on older python and has older ca-certificates. This way, not all HTTPs sites are validated properly. Can the dockerhub-build proces please be reinstated?

**Comment by cjmayo** [comment]
Docker images are available on GitHub:
https://github.com/linkchecker/linkchecker/pkgs/container/linkchecker

@anarcat - any ideas? Are you able to add a message on Docker Hub to point people to GitHub? Or disable / delete the Docker Hub account?

**Comment by anarcat** [comment]
i probably have access, let me take a look

**Comment by anarcat** [comment]
i *think* i have fixed this by updating the readme. .it seems i have access to that repo still. happy to grant my comaintainers access if you have a docker account, in case something like this happens again and i'm afk.

**Comment by wschoot** [comment]
Works for me.

Just my last $0.02, you might wanna delete the old tag (by navigating to that tag in Docker Hub) and select "Delete Tag" to avoid confusion with a three year old version.

**Comment by anarcat** [comment]
good idea, deleted, thanks.

**Comment by cjmayo** [comment]
Thanks both for raising and fixing - looks good to me. (I don't have a Docker Hub account).

**Comment by anarcat** [comment]
On 2022-07-06 10:27:32, Brendan Luchen wrote:
> Hey gang, just dropping in to advise that for downstream projects that depend on the old dockerhub image, the error message is somewhat opaque:
>
> ```console
> % docker image pull linkchecker/linkchecker
> docker: Error response from daemon: manifest for linkchecker/linkchecker:latest not found: manifest unknown: manifest unknown.
> ```
>
> Not grumpy - you did the right thing. It just happened to result in an annoying few extra minutes of digging. Hopefully by posting this comment here, search engines will pick it up, & others will find themselves here more easily.
>
> In a perfect world, dockerhub would respond clearly in the console that `this image is GONE and it won't be coming back. Please use the image located $THERE instead.` 😄 

Yeah, it would be great if Docker hub would allow us to do redirects
like this, but let's just say I won't hold my breath for that. :)

-- 
Music gives a soul to the universe, wings to the mind, flight to the
imagination and life to everything
                         - Plato
