### ISSUE TITLE
maxrequestspersecond description is misleading

### ISSUE THREAD

**Issue by cjmayo** [linkchecker/linkchecker#665]
Although it is true that 1 / `maxrequestspersecond` is the minimum interval between requests, the average rate is capped at 4 requests per second.

(Also related is #545 )

Originally reported by @pacenathan

**Comment by pacenathan** [comment]
Or you could think of this as the code has a bug and the documentation is correct. I.e. linkchecker has a hard cap of 4 requests per second, even though it is not documented to have such a cap. And it's a very bad idea for an automated link checking tool to have a hard cap on performance, especially one that's so painfully low.
