### ISSUE TITLE
strange escaping of url generate a 400 BAD REQUEST error

### ISSUE THREAD

**Issue by oupala** [linkchecker/linkchecker#71]
One of the url I'm trying to *linkcheck* is:

`http://webarchive.nationalarchives.gov.uk/20130129110402/http://www.hm-treasury.gov.uk/sternreview_translations.htm`

linkchecker is returning an error:

> Result	Error: 400 BAD REQUEST

The error mention the following requested url:

`http://webarchive.nationalarchives.gov.uk/20130129110402/http%3A/www.hm-treasury.gov.uk/sternreview_translations.htm`

As you can see, the `http://` in the middle of the url has been translated to `http%3A/`.

I think that might explain the error!

**Comment by oupala** [comment]
This might be related to #23

**Comment by cjmayo** [comment]
This does indeed appear to be fixed, tested on the latest git version.

Do reopen if there are still problems.

**Comment by oupala** [comment]
Thanks for the fix.

If I'm not used to python, what is the best way to test the git version of linkchercker?

I usually use linkchecker using the debian package, or the docker image.

**Comment by cjmayo** [comment]
This was fixed in 9.4, so if that works for you fair enough.

The only recommended way to get the current code is:
`pip3 install git+https://github.com/linkchecker/linkchecker.git`

**Comment by oupala** [comment]
Great thanks!
