### ISSUE TITLE
Default to checking external links in GUI and command prompt

### ISSUE THREAD

**Issue by Kisty** [linkchecker/linkchecker#79]
I want to test a root of multiple HTML files and check external links. Really surprised that the GUI doesn't automatically default to this, or at least, have it as an option. I would have thought it would default to this. It's an option on the command line, but not in the GUI. Any chance this can be enabled by default?

Related to #78

**Comment by cjmayo** [comment]
The GUI has been removed from this project.
And no, I don't see checking external links becoming the default.
