### ISSUE TITLE
User Configurable max byte size?

### ISSUE THREAD

**Issue by bexelbie** [linkchecker/linkchecker#80]
I would swear I read that someone had submitted a patch to allow users to up the max_bytes of each page checked.  I can't find this reference.

Is there interest in this?

**Comment by cjmayo** [comment]
You remember correctly and it wasn't documented.

I've proposed the following documentation in https://github.com/linkchecker/linkchecker/pull/470:

**maxfilesizedownload=** *NUMBER*
    Files larger than NUMBER bytes will be ignored, without downloading anything
    if accessed over http and an accurate Content-Length header was returned.
    No more than this amount of a file will be downloaded.
    The default is 5242880 (5 MB).
    Command line option: none
**maxfilesizeparse=** *NUMBER*
    Files larger than NUMBER bytes will not be parsed for links.
    The default is 1048576 (1 MB).
    Command line option: none
