### ISSUE TITLE
AnchorCheck can't handle modern anchor specs, only works with `<a name=...>`

### ISSUE THREAD

**Issue by stas00** [linkchecker/linkchecker#816]
## Summary

AnchorCheck works well to verify `<a name="foo">` anchors, but this HTML feature has been deprecated as stated [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#name).

For example github.com has just recently stopped using this deprecated `name` attribute, moving to `id` instead and now the link checker reports 100% failure on anchor check which is 100% false.

## Steps to reproduce

```
$ cat linkcheckerrc
[output]

[AnchorCheck]
```
then:
```
$ linkchecker --config build/linkcheckerrc https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-ulysses#significant-communication-volume-reduction --check-extern
URL        `https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-ulysses#significant-communication-volume-reduction'
Real URL   https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-ulysses#significant-communication-volume-reduction
Check time 0.777 seconds
D/L time   0.158 seconds
Size       190.50KB
Warning    [None] Anchor
           `significant-communication-volume-reduction' (decoded:
           `significant-communication-volume-reduction') not
           found. Available anchors:
           `action-menu-86adf8cb-d327-4e98-84f1-dea6b7e2e548-button',
[...]
```

The anchor is correct - it's easy to see by clicking on https://github.com/microsoft/DeepSpeed/tree/master/blogs/deepspeed-ulysses#significant-communication-volume-reduction

## Environment

 * Linkchecker version: LinkChecker 10.4.0 released 2023-12-11

Thank you.

**Comment by shepherdjerred** [comment]
Anchorcheck definitely supports `id` attributes. The anchor `significant-communication-volume-reduction` does not actually exist in the HTML source of the page you linked (you can check this yourself). It must be created with JavaScript.

**Comment by stas00** [comment]
Thank you for confirming that `id` is supported, @shepherdjerred 

You were correct that the id is there but hidden inside a javascript buffer:

```
 id=\"user-content-significant-communication-volume-reduction\"
```

As I can see `linkchecker` doesn't support javascript, any suggestions to how to overcome this hurdle? github.com is a huge website. Do you think I could try to file an Issue somewhere with github?

**Comment by shepherdjerred** [comment]
If you don't need to verify a lot of GitHub links, then I would just exclude this link from your configuration (there's a setting to ignore by regex).

Otherwise, you could try opening an issue... somewhere? I don't know where GitHub takes feature requests.

**Comment by stas00** [comment]
Understood. I was hoping that you might know where, but I will search for it.

Thank you very much for your helpful commentary so far, Jerred.

I'm closing this then.
