### ISSUE TITLE
Retry to contact wummel for moving/Closing/allowing access to old repo

### ISSUE THREAD

**Issue by dpalic** [linkchecker/linkchecker#91]
I will give it a new try to contact wummel. Hopefully I can find a way to close the original repo along with the option to reference to this new organisation of linkchecker.
I will inform you further

**Comment by anarcat** [comment]
thanks!

**Comment by rayjolt** [comment]
I just tried emailing Wummel. One of the email addresses he used for the repository was dead (the deian.org one), but another one worked (the web.de one). I also found another email address on Google that I think belongs to him, and I tried emailing that too. Let's see if there's any response.

**Comment by dpalic** [comment]
great idea, but I did it already with no success as I posted this issue.
A friend of mine is a business colleague of him, which is still open, so maybe we will get some results over the direct way. Even if we have not got any response on this so far.

**Comment by anarcat** [comment]
@dpalic any results from talking to @wummel directly? it would be great to gain access to the repository, if only to fix the old website to point to the new one...

**Comment by dpalic** [comment]
sadly all my tries to get in touch with him (even through a collegue of him) failed.
The only option is to ask the linux distributions to replace the old linkchecker with the new from this repo.

**Comment by anarcat** [comment]
well that's unfortunate, but we tried! the linux distro switch is well underway, see #136 for progress. the only true blocker we have left is the PyPI release, and that will be fixed once those folks process their backlog...

so @wummel, as always, you are very welcome here and we would love to hear from you. i am happy to learn that you are still alive and well at least. :)
