### ISSUE TITLE
Stopped finding broken links

### ISSUE THREAD

**Issue by mrkaban** [linkchecker/linkchecker#94]
Hello, there is a site https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/, used to find broken links on it, but now has stopped. It seems that I did not change anything in the settings of the program, not on the site.

The following important parameters are set in the configuration:
sslverify=0
allowedschemes=http,https

Prompt please, I can not understand. Very handy program!

**Comment by anarcat** [comment]
please try again with the latest release (9.4.0).

**Comment by mrkaban** [comment]
For Windows it is planned to build? or is the program now only for Linux?

At me it is simple only Windows =(

**Comment by anarcat** [comment]
i understand: we do not have windows builds anymore, but we want to fix this, see #53 for a followup on that.

**Comment by mrkaban** [comment]
I understand, thank you very much, I will wait!

I'll try to install Linux on a virtual machine and check the problem, which is indicated in this ticket, I will write the result!

**Comment by cjmayo** [comment]
Do retry with the latest software:
`pip3 install git+https://github.com/linkchecker/linkchecker.git`

It does install on Windows these days, see https://github.com/linkchecker/linkchecker/blob/master/doc/install.txt for a few ideas.

and open a new issue if there is still a problem. If reporting an issue do include the errors output.
