### ISSUE TITLE
Icon for Windows executable is incorrect

### ISSUE THREAD

**Issue by goozak** [linkchecker/linkchecker#99]
[issue originally [posted](https://github.com/wummel/linkchecker/issues/696) in 'old' repo.]

The correct icon is used for the main window of the app (bottom one in the screenshot below), but not for the executable (linkchecker-gui.exe) — which is the one used by Windows in the task bar.

I guess it doesn't really matter for the command-line executable (linkchecker.exe).

![linkcheckericon](https://user-images.githubusercontent.com/454810/32172503-39464c0e-bd52-11e7-97b3-1875d39227f7.png)

**Comment by cjmayo** [comment]
The GUI has been removed from this project and no binaries are currently supplied.
